### ISSUE TITLE
Support actions with transition via choice/junction pseudostate

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-statemachine#108]
This `Pseudostate` should not have any actions associated with it but it might make sense to have `Action` with transition leading into and out from the state itself.

**Comment by rgreig** [comment]
This would be very useful. In many cases in the choice pseudostate, you might have a relatively expensive calculation to perform to determine the target state you want to go into. If you try to do this on guards you end up executing that expensive operation multiple times. If you can execute an action going into the pseudostate, you can make it much more efficient by doing all the logic once and setting a variable or adding a field to the header, and then the guards become trivial.

I have read the UML spec for this (2.5) and I don't believe this goes against anything in the spec.

**Comment by jvalkeal** [comment]
What I've been thinking is to add actions to `source`, `first`, `then` and `last` methods.
```
ChoiceTransitionConfigurer<S, E> source(S source);
ChoiceTransitionConfigurer<S, E> source(S source, Action<S, E> action);
ChoiceTransitionConfigurer<S, E> source(S source, Action<S, E> action, Action<S, E> error);

ChoiceTransitionConfigurer<S, E> first(S target, Guard<S, E> guard);
ChoiceTransitionConfigurer<S, E> first(S target, Guard<S, E> guard, Action<S, E> action);
ChoiceTransitionConfigurer<S, E> first(S target, Guard<S, E> guard, Action<S, E> action, Action<S, E> error);
```
Then javaconfig would look like:
```
.withChoice()
	.source(TestStates.S3, sIToChoice())
	.first(TestStates.S30, s30Guard(), choiceToS30())
	.then(TestStates.S31, s31Guard())
	.then(TestStates.S32, s32Guard())
	.last(TestStates.S33, choiceToS33(), choiceToS33Error());
```
With uml you'd just add behaviours to those incoming/outgoing transitions so it looks a bit simpler to configure. I didn't see no reason why outgoing vertex could not have action as well.

**Comment by jvalkeal** [comment]
Merged per https://github.com/spring-projects/spring-statemachine/commit/cec0d2403570aa60d0605ca06f237e3acd13a37a

**Comment by gaurav11007** [comment]
.withChoice()
	**.source(TestStates.S3, sIToChoice())**
	.first(TestStates.S30, s30Guard(), choiceToS30())
	.then(TestStates.S31, s31Guard())
	.then(TestStates.S32, s32Guard())
	.last(TestStates.S33, choiceToS33(), choiceToS33Error());

Is this functionality ( Action for Source ) available? If yes then since which version?
