### ISSUE TITLE
PersistStateMachineHandler initialization

### ISSUE THREAD

**Issue by tatabatyo** [spring-projects/spring-statemachine#109]
PersistStateMachineHandler could have a public initialize() method with the content of the current onInit() method, that can be called if the PersistStateMachineHandler is not injected, but manually created (for example in case I want to use StateMachineFactory and not a single StateMachine). 

Currently I could find no other way, but to use reflection to call the onInit() method.

**Comment by jvalkeal** [comment]
It's not really necessary because it already gets common method `InitializingBean.afterPropertiesSet()` from parent `LifecycleObjectSupport`. `afterPropertiesSet()` then calls `onInit()`. Call `afterPropertiesSet()` manually if you work outside of spring app context.

**Comment by tatabatyo** [comment]
Thanks, great advice!
