### ISSUE TITLE
spring-statemachine-data-jpa compatibility with Spring Boot 3

### ISSUE THREAD

**Issue by lukas99** [spring-projects/spring-statemachine#1103]
Hi

The latest version of Spring Statemachines Jpa definitions (artefact "spring-statemachine-data-jpa") isn't yet compatible with Spring Boot 3 and it's Jakarta baseline.

E.g. JpaRepositoryStateMachine.java still uses javax.persistence instead of it's Jakarta counterparts:
https://github.com/spring-projects/spring-statemachine/blob/main/spring-statemachine-data/jpa/src/main/java/org/springframework/statemachine/data/jpa/JpaRepositoryStateMachine.java

Are there plans to support Spring Boot 3 with it's Jakarta baseline?
Would it be possible to publish another artefact of spring-statemachine-data-jpa using Jakarta imports? E.g. with name spring-statemachine-data-jpa-jakarta

Kind regards
Lukas

**Comment by libinbin880521** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by egreijus** [comment]
There is a pull request for upgrading to 3 (https://github.com/spring-projects/spring-statemachine/pull/1104). Obviously there is more work that has to be done apart from the pull request to have it build on JDK 17 but this should be a good starting point.

**Comment by jvenki** [comment]
Any update on when the PR will get merged and pushed

**Comment by andreas-schilling** [comment]
PR is merged, (pre-)release date yet pending: https://github.com/spring-projects/spring-statemachine/pull/1104
