### ISSUE TITLE
Support use of session @Scope

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-statemachine#112]
As a user I'd like to be able to use a state machine instance with a `@Scope`.

**Comment by diego522** [comment]
Any answer about this?

**Comment by jvalkeal** [comment]
Nope, not yet. I have done some prototyping but don't have anything working right now.

**Comment by jvalkeal** [comment]
Paging @diego522 lemmy know what you think about a fix I just committed. I wrote something to docs but [SessionScopedAnnotationTests](https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/test/java/org/springframework/statemachine/config/SessionScopedAnnotationTests.java) and [SessionScopedManualTests](https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/test/java/org/springframework/statemachine/config/SessionScopedManualTests.java) also shows how things work. It was a relatively small change so I think it's ok for 1.0.2, we can then do more tweaks for 1.1.0.

**Comment by diego522** [comment]
I have a question, I have a process with multiple users, and I'm thinking create a machine with prototype scope, is valid for me this?
I need to know if I have multiple users this doesn't affect the machine states.

make sense??
