### ISSUE TITLE
Overhaul gradle build

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-statemachine#1143]
Build should be overhauled to be aligned with more modern gradle concepts. This is basically what has happened in all spring projects using gradle.

Essentially moving away from plain full dsl's in favour of buildSrc.

**Comment by rishiraj88** [comment]
Will gradle wrapper not suffice? the question may be quite humble or high level, pardon me if it is so.

**Comment by jvalkeal** [comment]
It's normal gradle build but moving most of a plugin configurations into buildSrc. Basically how build works in `spring-boot` and `spring-shell`.
