### ISSUE TITLE
WithStateMachine.name not being used

### ISSUE THREAD

**Issue by fabiofalci** [spring-projects/spring-statemachine#116]
Hi,

I've been trying to use `WithStateMachine.name` to have more than one statemachine at the same time but `OnTransition` methods is being called on both beans even if I use `WithStateMachine.name`.

I've created this test to demonstrate the issue. Please evaluate if my thinking is correct.

https://github.com/fabiofalci/spring-statemachine/commit/221b9d5910883ca4af2304e57e8c620efaffe004

**Comment by jvalkeal** [comment]
Thanks for the unit test. Lemmy play with that because if it indeed behaves like you just mentioned it's a bug.
