### ISSUE TITLE
End of Support for the framework?

### ISSUE THREAD

**Issue by buechech** [spring-projects/spring-statemachine#1161]
Hi,

I'm looking at the Support documentation, and v4.0 is marked [End of Support in Dec. 2024](https://spring.io/projects/spring-statemachine#support). I don't see a subsequent version listed - Is this the end of support for the spring-statemachine framework entirely? If so, are there suggestions for alternative state machine frameworks?

Thanks,
Christian

**Comment by keeslips** [comment]
I'm also interested in the activity of the spring state machine project. We just started to use it and really want to keep on using it in the near future. Otherwise we have to look for another way of handling our processes in our application. Hope for some good news, that state machine is there already for sometime and does a good job, lots of information and work done.

**Comment by phonty29** [comment]
I hope for the support of this project

**Comment by mehmetsalgar** [comment]
First let me say, I have no affiliation with Spring State Machine project and I don't know their plans how to proceed with SSM support...

I am just writing to answer this question,

>are there suggestions for alternative state machine frameworks?

For my experience, the state machines with Enterprise level of support and capabilities are

[Pekko Finite State Machine](https://pekko.apache.org/docs/pekko/current/typed/fsm.html)

or 

[Camunda](https://camunda.com/)

Specially Camunda V7 is really similar to Spring State Machine, you will see that is presented as Workflow Engine but I can do everything I do with SSM in Camunda....

Camunda V8 is little bit more Server / Client design for k8s / Cloud but you can operate V7 very similar to SSM.

Pekko is not that user friendly, it has no direct support of using Eclipse Papyrus for UI Design of an UML State Machine but I wrote a blog how to generate configuration information from Eclipse Papyrus for Pekko, [here](https://mehmetsalgar.wordpress.com/2022/04/18/a-model-driven-event-sourced-cloud-ready-application-with-akka-finite-state-machine-using-kafka-cassandra-and-elasticsearch/) the link if it would be useful for anybody.

**Comment by buechech** [comment]
I love how this was never acknowledged or answered, but someone pushed back the End of Support to November 2025 without telling anyone.

![Uploading image.png…]()

**Comment by libinbin880521** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by winfriedgerlach** [comment]
@jvalkeal @fmbenhassine you seem to be the only contributors over the last 12 months - is this project dead? If not, when can we expect at least a maintenance release? It's a bit odd that this component sees so little love while Spring/Boot are pushing new releases over and over...

**Comment by fmbenhassine** [comment]
Hi All,

While the project has had little activity during the previous months (due to internal reasons), it is definitely not dead! I will be leading the effort to maintain Spring State Machine starting 2025, and the community can expect a maintenance release of the latest line in Q1 2025. The [support page](https://spring.io/projects/spring-statemachine#support) has been updated and the v4 line will be supported until 2025-11-21 (same as Spring Boot 3.4.x).

I am excited to share this news with the community and I am looking forward to working with you all!

Best regards,
Mahmoud

**Comment by mollydi** [comment]
> Hi All,
> 
> While the project has had little activity during the previous months (due to internal reasons), it is definitely not dead! I will be leading the effort to maintain Spring State Machine starting 2025, and the community can expect a maintenance release of the latest line in Q1 2025. The [support page](https://spring.io/projects/spring-statemachine#support) has been updated and the v4 line will be supported until 2025-11-21 (same as Spring Boot 3.4.x).
> 
> I am excited to share this news with the community and I am looking forward to working with you all!
> 
> Best regards, Mahmoud

Glad to see this. And when will SSM support the AOT feature?

**Comment by fmbenhassine** [comment]
@mollydi It should be possible to natively compile a SSM app. I will check the current state things and add a comment on #1080

**Comment by fmbenhassine** [comment]
Hi,

I just wanted to share an update about the project status here:

https://spring.io/blog/2025/04/21/spring-cloud-data-flow-commercial#comment-6692389437

**Comment by ouaibsky** [comment]
Hi

@fmbenhassine Waht does it means for this repository and all PR ongoing ?
Thx
Chris.

**Comment by fmbenhassine** [comment]
@ouaibsky That means we are going to support the current 4.0.x branch with patch releases until it is out of OSS support, then move the project to the attic (Please check the [support policy page](https://spring.io/projects/spring-statemachine#support)).

Regarding contributions, we might consider merging some PRs if they can be included in patch releases.

**Comment by winfriedgerlach** [comment]
@fmbenhassine so when will we finally get a patch release? spring-statemachine-core still references outdated, vulnerable `spring-tx` and `spring-messaging` versions...

**Comment by fmbenhassine** [comment]
@winfriedgerlach We are waiting for Spring Boot 3.5.0 (planned for today) to include it in the upcoming v4.0.1 and which should update these outdated dependencies.

**Comment by fmbenhassine** [comment]
@winfriedgerlach This definitely has taken more time than expected due to outdated build and release processes. I will make that a priority to get SSM 4.0.1 out based on Spring Boot 3.5.1. Thank you for your comprehension.

**Comment by winfriedgerlach** [comment]
@fmbenhassine meanwhile it is Spring Boot 3.5.3 ;-)
