### ISSUE TITLE
EnableStateMachineFactory fails when there are 2 state machine configurations

### ISSUE THREAD

**Issue by mehmetsalgar** [spring-projects/spring-statemachine#117]
Previously I build a feasibility application to integrate Spring Web Flow and State Machine concepts together. At the time I wrote that application there wasn't a commercial or open source state machine implementation that I can use and fit my requirements, so I implemented my own.

Now that I discovered Spring-Statemachine I am in the process of converting the application to use the Spring-Statemachine but I am encountering some problems.

I need in my application several state machine configurations because I need them in master and slave modes (you can read the concept here - https://mehmetsalgar.wordpress.com/2014/05/22/extremely-ajaxified-web-application-with-spring-webflow-primefaces-and-state-machines/#master_slave).

As long as I annotate the configurations there is no problem @EnableStateMachine but the moment I annotate multiple configurations with @EnableStateMachineFactory Spring is not able to initialize the application context with the following exception.

[code]Caused by: java.lang.NullPointerException: null
	at org.springframework.statemachine.config.configuration.StateMachineFactoryConfiguration$StateMachineFactoryDelegatingFactoryBean.afterPropertiesSet(StateMachineFactoryConfiguration.java:111)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1631)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1568)[/code]

I try to read the code, I have a feeling it is happening because Spring is in the process of initializing the factory for the first state machine and if the 2nd state machine tries to initialize itself during the building state this error happens.

I can't clearly say, I have built a sample maven project that reproduces the problem (I had to fake the extension to png to be able to upload but actually it is a zip).

In the project you will see a "Driver.class" to test the behavior, if I am misusing a concept for the configuration of state machines , please let me know I will try to adapt.

I need the master/slave concept because I a giving the responsibility of communicating with partner systems to the slave machines and it is possible to have calls to these systems over multiple threads, so it is essential that I get multiple instances of the state machine from the factories to control the behavior at every thread and there will be multiple state machine configurations in the system.

On additional thing that am curious about it, it seems that it is not possible to initialize state machines or factories in @Lazy mode or? As I said I will initialize several state machines/factories but I don't need them all at application start so an option to initialize them lazily will be nice actually and may be a scope element in the @EnableStateMachine annotation.
![factory-proof](https://cloud.githubusercontent.com/assets/433232/10964557/1e71e05e-83a8-11e5-8724-188351961a2b.png)

**Comment by jvalkeal** [comment]
Thanks for pointing this out! I was able to reprod this and will get it fixed.

`StateMachineFactory ` is one way to build multiple machines but there is also builder pattern model which can be used to build machines manually which is mentioned in docs or i.e. in this test https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/test/java/org/springframework/statemachine/config/ManualBuilderTests.java.

Builder is usually used if there is no need for spring context integration or generally if machine is not created as bean.

**Comment by jvalkeal** [comment]
@mehmetsalgar I was missing a test for this case so bug was left in place, so very good that you found it and posted a ticket. Fix was easy because it was basically my mistake that I originally left something out from classes handing factory annotation building.

Feel free to try master. There's been few other fixes so I might fire up 1.0.1.RELEASE next week.

Thanks mate!
