### ISSUE TITLE
Reference doc: error in sample code for 16.1 Annotation Support

### ISSUE THREAD

**Issue by pgifford** [spring-projects/spring-statemachine#123]
In the code for `@StatesOnTransition`, `static` is not valid in the class definition.  It should read something like:

```java
public @interface StatesOnTransition {
```
I know this is minor. I'd submit a roll-up of errors I've found in the sample code but the reference documentation is very good...this is the only error I've run into while working through it!

**Comment by jvalkeal** [comment]
Yeah that's true. Samples are imported into docs from source files and this from https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/test/java/org/springframework/statemachine/docs/DocsConfigurationSampleTests.java#L422. In that source file it's inner class and `static` is valid there.

However it's a good point. I'll think how to clarify these if user just tries to copy/paste these from docs.
