### ISSUE TITLE
Additional functionality on StateMachineListenerAdapter

### ISSUE THREAD

**Issue by mehmetsalgar** [spring-projects/spring-statemachine#132]
StateMachineListenerAdapter contains the method 'eventNotAccepted' to track an event is received but not transition found for it.

I think it will be also useful to have a method stating for the received event a transition(or several transitions) is found but guard conditions didn't let the transition occurs.

This information would be extremely useful at the initial development stages of the state machine when not all uses cases are known and also in production when system receives condition that is previously not forseen.

At the moment state machine is finding transitions but while none of them succeeds and state machine stays silent.

A concrete example, we are at STATE_A and receive EVENT_A there are transitions TRANSITION_A (with guard condition checking foo==1) which will lead to STATE_B and TRANSITION_B(with guard condition checking foo=2) which will lead to STATE_C. State machine received EVENT_A but foo is 3 so no transition occurs and state machine does not log or send a signal that it didn't occur.

If there will be no Transition for EVENT_A then the method 'eventNotAccepted' will trigger but not for this case.

Usually when this occurs this means an unknown use case for the state machine and it will be nice to give a signal so developer/implementer can improve the design of its state machine.

**Comment by jvalkeal** [comment]
Yes I agree that this scenario is something we need to handle. Not yet sure if adapter or listener is a proper place for this as is, but definitely user should get more info about _why_ event was not accepted. Lemmy think about this a little which probably then results a few gh issues.

**Comment by mehmetsalgar** [comment]
Can you also add the information to method 'eventNotAccepted(Message<CustomerSearchSM_EventEnumerationImpl> event)' about the current state and a way to access to extendedState

I think the best will be to give access to StateContext in this method or the feature methods, or at least read only/immutable version of this object.

**Comment by jvalkeal** [comment]
paging @mehmetsalgar, would you mind review stuff done with #150 i.e. http://docs.spring.io/spring-statemachine/docs/1.1.0.BUILD-SNAPSHOT/reference/htmlsingle/#sm-statecontext and listener `stateContext()` method. Hopefully this gives enough ammos to deliver needed features.

**Comment by mehmetsalgar** [comment]
sure but did you published the 1.1.0.BUILD-SNAPSHOT to any maven repository or have to build from github?

**Comment by jvalkeal** [comment]
Yes, snapshots goes to http://repo.spring.io/libs-snapshot/org/springframework/statemachine/spring-statemachine-core/

**Comment by mehmetsalgar** [comment]
Ok, I have 2 bad news...

First, I have modified my code to use new functionality....

public StateMachineListener<CustomerSearchSM_StateEnumerationImpl, CustomerSearchSM_EventEnumerationImpl> listener() {
		return new StateMachineListenerAdapter<CustomerSearchSM_StateEnumerationImpl, CustomerSearchSM_EventEnumerationImpl>() {
			@Override
			public void stateChanged(
					State<CustomerSearchSM_StateEnumerationImpl, CustomerSearchSM_EventEnumerationImpl> from,
					State<CustomerSearchSM_StateEnumerationImpl, CustomerSearchSM_EventEnumerationImpl> to) {
				LOG.info("State change to " + to.getId());
			}

			@Override
			public void eventNotAccepted(Message<CustomerSearchSM_EventEnumerationImpl> event) {
				LOG.warn("The event " + event.toString() + " is not accepted!");
			}

			@Override
			public void stateContext(StateContext<CustomerSearchSM_StateEnumerationImpl, CustomerSearchSM_EventEnumerationImpl> stateContext) {
				if(stateContext.getStage().equals(StateContext.Stage.EVENT_NOT_ACCEPTED)) {
					LOG.warn("For state: " + stateContext.getSource().getId() + " event: " + stateContext.getEvent().getEventName() + " is not accepted!");
					LOG.warn("The current values of the Extended State" + stateContext.getExtendedState().toString());
				}
			}
		};
	}

as you can see with 'public void stateContext(....)' first problem, the check 'if(stateContext.getStage().equals(StateContext.Stage.EVENT_NOT_ACCEPTED))' is always returning true. 

Is it possible StateContext.Stage.EVENT_NOT_ACCEPTED as default value set?

2nd, if you look to the LOG statements I am trying to access source state.

LOG.warn("For state: " + stateContext.getSource().getId() + " event: " + stateContext.getEvent().getEventName() + " is not accepted!");

considering I got a 'EVENT_NOT_ACCEPTED' source state is null, I mean if there is an event, source must be always there I think but this is not worst part.

While it is null, a NullPointerException happens here but the state machine is not 'running to completion', it just breaks up here. In my opinion such utility methods like 'listeners' should never endanger the 'Run-to-Completion' state machine should log the problem but should continue to work.

**Comment by jvalkeal** [comment]
ok, thanks for comments. These has been relatively large changes internally and it takes some time to iron out all the bugs and make concepts around it consistent. I'll create new issues for these.

**Comment by jvalkeal** [comment]
Closing this now that there's been fixes for these in other tickets.

**Comment by subratadey03** [comment]
Hi, We upgraded StateMachine to 4.0.0, we are also getting this "eventNotAccepted" many places.
`2024/03/25,14:14:12.895 WARN  [DeviceBroker   ] [Thread-78      ] .device.base.statemachine.BaseStateMachineListener : [eventNotAccepted] Device- POSPrinter event not accepted: GenericMessage [payload=COVER_OPEN, headers={id=e4e7dcff-bf61-10cc-676e-367a97fa8f4a, timestamp=1711356252893}] `

But we are successfully getting the event as well as state also changing.

Earlier we used to get : `2023/12/20,13:48:06.600 INFO [DeviceBroker ] [nio-8080-exec-7] mework.statemachine.support.LifecycleObjectSupport `
Is it expected in 4.0.0 ? 

If it is a bug which version we need to upgrade ? or do we need to change anything in our implementation ?
