### ISSUE TITLE
Pass StateContext to StateMachineListener methods

### ISSUE THREAD

**Issue by pgifford** [spring-projects/spring-statemachine#138]
It would be very handy to have `StateMachineContext` or `ExtendedState` passed as a parameter to all `StateMachineListener` methods.

We use a `StateMachineFactory` that is configured to use an `@Autowired StateMachineListener` bean.  When `stateChanged` fires, for example, we don't know which state machine changed state.  As a workaround we could give our listener bean prototype scope but it would be simpler to be able to access the variables in the extended state.

**Comment by jvalkeal** [comment]
Original idea back in days was that you would not interact with machine from a listener so all those goodies were left out. Thought I can't really stand behind that argument any more because there are other parts which are already exposing those. #126 will overhaul whole annotation model with 1.1.x and in a sense annotated method is already a listener callback.

Can't really change existing listener methods order to keep backward compatibility, but perhaps adding secondary methods or doing some other tricks not to bloat interface too much.

**Comment by pgifford** [comment]
I don't want to interact with the machine, I only want to access its entire (i.e. including extended) state, and really only the variables in the state. The variable map could be made unmodifiable, though the values inside the map could still be changed.  It's a tricky problem, with us users trying to break everything :)

I have a couple of ideas about how the listener interface could be enhanced, both of which involve creating an event object akin to the old `java.awt.event.*` event objects.  I'd suggest `StateMachineEvent` for a name but that's already taken. `RegionEvent`, perhaps?  Anyway, the object would encapsulate the full state of the machine at the time of the event.

With that event object in hand the existing listener methods could be overloaded to take the event object as a parameter, so all listener events would receive that object.  If that adds too many methods then maybe a single "somethingHappened" method could be added to the listener (though with a better method name) which would receive the event object, though to do this the type of event would have to be included in the event object.

**Comment by jvalkeal** [comment]
It's interesting idea to use events in a listener. `StateMachineEvent` and its subclasses go hand-to-hand with listener methods so it might be a good idea to play with this idea. Those event classes are much easier to change than a listener interface itself. I'll see how well it plays out.

**Comment by jvalkeal** [comment]
Actually it should be `StateContext` not `StateMachineContext` which is used in serialization and is a different beast. Anyway I'm doing work with #126 which needs everything this issue needs and will get supported. I initially had some trouble(mostly with generics) when I did some prototyping, but I'll get it sorted out somehow.

**Comment by jvalkeal** [comment]
Marking this fixed as base work has been completed, other issues in separate tickets.
