### ISSUE TITLE
notifyTransition and notifyTransitionEnd call wrong publish methods

### ISSUE THREAD

**Issue by jmu** [spring-projects/spring-statemachine#144]
is that a problem ?

	protected void notifyTransition(Transition<S,E> transition) {
		stateListener.transition(transition);
		if (contextEventsEnabled) {
			StateMachineEventPublisher eventPublisher = getStateMachineEventPublisher();
			if (eventPublisher != null) {
				eventPublisher.publishTransitionEnd(this, transition);
			}
		}
	}

	protected void notifyTransitionEnd(Transition<S,E> transition) {
		stateListener.transitionEnded(transition);
		if (contextEventsEnabled) {
			StateMachineEventPublisher eventPublisher = getStateMachineEventPublisher();
			if (eventPublisher != null) {
				eventPublisher.publishTransition(this, transition);
			}
		}
	}

**Comment by jvalkeal** [comment]
Thx for pointing this out. It's clearly a very dummy mistake from my part. I'll get it fixed into next release.
