### ISSUE TITLE
Listener error should not cause malfunction

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-statemachine#164]
As any callback, event or listener may potentially throw errors, machine should catch those and not malfunction.

**Comment by mehmetsalgar** [comment]
I see what you did here would not be better here to have Throwable in catch statement then the Exception.

As I mentioned, State Machine can't break the 'Run to Completion' principle for any error type.

**Comment by jvalkeal** [comment]
Right that is a good point indeed.
