### ISSUE TITLE
@OnTransition Annotations are not effective in Unit tests

### ISSUE THREAD

**Issue by johnmerm** [spring-projects/spring-statemachine#169]
I Import the "@EnableStateMachine" configuration in the Unit test and run it. The "@WithStateMachine" bean "@OnTransition" methods are not executed

When I use a main Method from the src code flow works OK.

Reproducibe with eclise & mvn test

**Comment by johnmerm** [comment]
<dependency>
			<groupId>org.springframework.statemachine</groupId>
			<artifactId>spring-statemachine-core</artifactId>
			<version>1.0.2.RELEASE</version>
		</dependency>

**Comment by jvalkeal** [comment]
You need to show your code. There is two things to remember, state machine needs to know a bean factory and bean with `@WithStateMachine` needs to be registered with that same bean factory.

You see this i.e. in https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/test/java/org/springframework/statemachine/processor/AnnotatedMethodTests.java

**Comment by johnmerm** [comment]
Solved it. I was calling stateMachine.start() from the post constructor of another bean. When I changed it to calling start() from the @Before of the test, the problem was solved.

The code is available in https://github.com/johnmerm/sipstatemachine. I'm building a SIP State machine
