### ISSUE TITLE
How to catch exception thrown by SSM actions?

### ISSUE THREAD

**Issue by louxl** [spring-projects/spring-statemachine#177]
Hi, 

we are using SSM in our project and SSM is launched within a transaction. Due to the task executor working mode, we are not able to catch exceptions thrown by the executor because they run under different threads. So even the action of state machine failed, we could not rollback this transaction.

Any hint on this situation? Any help will bre appreciated.

Again, thanks for this elegant framework.

**Comment by jvalkeal** [comment]
This is a case where we probably need to pay more attention. I understand where you're going with this but currently, imho, it doesn't make that much sense to send events to SSM within a transaction. Transactions are thread bounded so you'd get into trouble(in a generic terms) with multiple threads anyway.

I really don't have any answer to this right now, but I'll play with things a little to see if there's any good solutions.

**Comment by louxl** [comment]
Great, thanks for your reply.
Please let me know if there is any progress.

**Comment by jvalkeal** [comment]
Closing as more detailed work/discussion is happening in #240
