### ISSUE TITLE
Support @WithStateMachine as meta annotation

### ISSUE THREAD

**Issue by aldib** [spring-projects/spring-statemachine#179]
If I create a specialised version of @WithStateMachine, e.g.
```java
@Target({ ElementType.TYPE, ElementType.METHOD })
@Retention(RetentionPolicy.RUNTIME)
@WithStateMachine(name = "")
public @interface WithTask {
}
```

The method [StateMachineAnnotationPostProcessor#isStereotype](https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/main/java/org/springframework/statemachine/processor/StateMachineAnnotationPostProcessor.java#L257) will not find the `@Component` annotation.

**Comment by jvalkeal** [comment]
Ok, fair enough, I can implement it.
