### ISSUE TITLE
Error Handling does not work when using annotations

### ISSUE THREAD

**Issue by aldib** [spring-projects/spring-statemachine#180]
The approach described in  [State Machine Error Handling](http://docs.spring.io/spring-statemachine/docs/1.1.0.M1/reference/htmlsingle/#sm-error-handling) does not work when using annotated methods. When an exception occurs it is propagated up rather than intercepted. I tried using the interceptor, the listener and the @OnStateMachineError without any success. Debugging the code, neither [MethodInvokingStateMachineRuntimeProcessor.java:52](https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/main/java/org/springframework/statemachine/processor/MethodInvokingStateMachineRuntimeProcessor.java#L52) or any of its callers have any specific logic to handle errors.

Replicating the issue is simple, just create a state machine (I'm using the latest snapshot) and register the bean:
```java
@WithStateMachine
public class ExceptionThrowingAction {
    @OnTransition
    public void throwError(@EventHeaders Map<String, Object> headers, ExtendedState extendedState) {
        throw new RuntimeException("test error");
    }
}
```

**Comment by jvalkeal** [comment]
Yes, good point indeed. I'll figure out how to handle this as it's a user code and should be handled in a same way than if listener callbacks are throwing errors.

In near term we probably just need to implement catch and log, but at some point we may want to add more sophisticate features for a SSM to dispatch these into an error handler(which we don't yet have) and then possibly put SSM into an error state if user doesn't handle it. Relatively complex topic which is something I'd like to get feedback from community of how these should actually work.

**Comment by jvalkeal** [comment]
I'm about to push a fix for this which will allow all annotations to get processed even if those are throwing errors. More sophisticated error handling is done in other issue #183.
