### ISSUE TITLE
AbstractStateMachine#resetStateMachine does not work if state is not of type String

### ISSUE THREAD

**Issue by aldib** [spring-projects/spring-statemachine#181]
Line [AbstractStateMachine:512](https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java#L512) never evaluates to true if the state ids are not of type String.
That is because `ss.getIds()` will return a collections of objects with the correct type (e.g. enum) while the `state` is always a string.

**Comment by jvalkeal** [comment]
Are you referring to [AbstractStateMachine:505](https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java#L505)
```
S state = stateMachineContext.getState();
```
Which would be a same type via generics. Or is there something I'm missing here?

I know that eventually we need to be able to mix different type(events,states) of machines but that is another topic.

**Comment by aldib** [comment]
In the snippet

```java
		boolean stateSet = false;
		for (State<S, E> s : getStates()) {
			for (State<S, E> ss : s.getStates()) {
				if (ss.getIds().contains(state)) {
					currentState = s;
					// TODO: not sure about starting submachine/regions here, though
					//       needed if we only transit to super state or reset regions
					if (s.isSubmachineState()) {
```
the line `if (ss.getIds().contains(state)) {` always return false because `ss.getIds()` is a collection of the enums (in my case) while the `state` variable seems to be always a string. Hence, `contains` does not work.

**Comment by jvalkeal** [comment]
If you have a sample to demonstrate this, it'd be a helpful.

**Comment by jvalkeal** [comment]
Or even better, a failing unit test ;)

**Comment by jvalkeal** [comment]
I'm going to mark this invalid and close it due to inactivity. Feel free to provide additional info which might demonstrate a problem as I'm simply unable to reproduce or understand this problem.
