### ISSUE TITLE
Support history state with persist

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-statemachine#182]
Currently there's is no way to persist history state so that should be implemented.

**Comment by jvalkeal** [comment]
Marking invalid per comment I made in http://stackoverflow.com/questions/35798302/create-a-statemachineinterceptor-to-persist-statemachinecontext

```
Hold on, regarding a question about a history state. As I created a #182 for it and started to work on it,
I couldn't figure out how to actually use it with a persistence. As history state is a transient and a pseudo state,
as it's simply tracking last known state, you can't really reset a machine into that state as its only job is to go
immediately into its last known state. So would you mind to elaborate what you meant by persisting a history 
```

**Comment by aldib** [comment]
There is a bug in [AbstractStateMachinePersister.java#L125](https://github.com/jvalkeal/spring-statemachine/blob/master/spring-statemachine-core/src/main/java/org/springframework/statemachine/persist/AbstractStateMachinePersister.java#L125). If the history is empty, `((HistoryPseudoState<S, E>)hh).getState()` will return null and `((HistoryPseudoState<S, E>)hh).getState().getId()` will throw a `java.lang.NullPointerException`

**Comment by jvalkeal** [comment]
Marking this fixed, additional issues in other tickets.
