### ISSUE TITLE
Ease persisting a state machine

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-statemachine#184]
Persistence is one relatively unknown topic for samples and docs when things gets more complicated. This issue is about making a simple helper class or api to easy whole persist operation regardless of a machine config or structure. Effectively we need to provide a glue between `StateMachine` and `StateMachinePersist`.

**Comment by aldib** [comment]
I'll be happy to help on this but I need some guidance as I'm still new to the existing design and implementation.

**Comment by jvalkeal** [comment]
@aldib sorry, didn't see your message until now. I think best way to help now would be to review what I've been doing on a master. There is new stuff around `StateMachinePersister` interface and use concepts in `StateMachinePersistTests` unit tests. Also eventservice sample is now using these new helper classes.

**Comment by jvalkeal** [comment]
Marking this fixed, additional issues in other tickets.
