### ISSUE TITLE
Persisting state machine id

### ISSUE THREAD

**Issue by aldib** [spring-projects/spring-statemachine#186]
It would be beneficial if it was possible to persist/restore the id of the state machine. My suggestions would be any of the following:
1. Add a setter in [StateMachine](spring-statemachine/spring-statemachine-core/src/main/java/org/springframework/statemachine/StateMachine.java) and let the user invoke it.
2. Add a method `StateMachineFactory#getStateMachine(String)` to [StateMachineFactory]( spring-statemachine/spring-statemachine-core/src/main/java/org/springframework/statemachine/config/StateMachineFactory.java ) to create a FSM with the given id
3. Store the id in [StateContext](spring-statemachine/spring-statemachine-core/src/main/java/org/springframework/statemachine/StateContext.java) and extend the [AbstractStateMachinePersister]( spring-statemachine/spring-statemachine-core/src/main/java/org/springframework/statemachine/persist/AbstractStateMachinePersister.java ) to manage it.

I would prefer solution 2 as it is simple to implement but still maintains the "read only" design of the [StateMachine](spring-statemachine/spring-statemachine-core/src/main/java/org/springframework/statemachine/StateMachine.java) interface.

**Comment by jvalkeal** [comment]
One trouble here is that this `id` is currently expected to be unique as i.e. `DistributedStateMachine` is using it to differentiate between distributed machines. Then substates and regions have their own id's which kinda helps to read logs.

Do you have a use case for this or is it just to make persistence less complicated?

**Comment by aldib** [comment]
The idea is that a FSM should be uniquely identifiable in a distributed environment regardless if it's active or not (persisted but not in memory) without the need of an additional business or surrogate keys.
I would like to be able to broadcast an event from any node (in my case using spring integration) and as long as the event contains the FSM id the receiving component should be able to materialise the  context and trigger the transition.
Maybe given that the id is already a UUID in text format, it would be worth changing the type java.util.UUID to stress the fact that has to be unique.

On a different topic, I haven't looked at `DistributedStateMachine` just yet but if the id is generated every time the machine is loaded from the store (or, how does the `StateMachineEnsemble` how know manage and events from `LocalEnsembleListener`?

Does the  `StateMachineEnsemble` need all the FSM to be in memory all the time?

**Comment by jvalkeal** [comment]
I think what you want is reasonable indeed. Current `id` which really is `uuid` is really only used within an individual machines to know if event originated from itself, thus checking if message headers contain its own machine id.

Maybe we could change current `id` to a real internal generated `uuid` and then let user to use `id` as he likes and expose feature to set that via config model. Like `getId()` would return user set `id` and `getUuid()` would return generated `uuid`.

Yes all machines in ensemble needs to be in memory, at least for now, but I don't see no reason why we could not lift that requirement. This is a relatively funky idea.

**Comment by jvalkeal** [comment]
@aldib regarding stuff in this ticket. If you want to check/review these before I merge, check PR #189. As these changes were driven by what you requested.
