### ISSUE TITLE
Restoring persisted context does not work with substates

### ISSUE THREAD

**Issue by aldib** [spring-projects/spring-statemachine#188]
When using a FSM with sub-states, the `DefaultStateMachinePersister` does not restore the machine to its original state. I wan not able to pinpoint the but but I attached a test case to reproduce the issue.
[spring-statemachine-bug.zip](https://github.com/spring-projects/spring-statemachine/files/182151/spring-statemachine-bug.zip)

**Comment by jvalkeal** [comment]
Yeah ok, I see same trouble with this sample. Thanks for the unit tests. I'll try to figure why it doesn't work.

**Comment by jvalkeal** [comment]
@aldib relatively dump mistake from my part. I had a too naive test for this history persist/reset, yours was much better. Pushed a fix per https://github.com/spring-projects/spring-statemachine/commit/a82ff5b93654215baa63a3f9c3af0ad693a9f2e1. At least locally here your test now passes with master. I also ported that test from your bug sample.

If you confirm, I can then close this issue.

**Comment by aldib** [comment]
I can  confirm that the bug is fixed in master. Thank you.

P.S. purely syntactical sugar, `StateMachineContext#getChilds()` should be `StateMachineContext#getChildren()`
