### ISSUE TITLE
Subsequent choice states are not evaluated in sequence

### ISSUE THREAD

**Issue by aldib** [spring-projects/spring-statemachine#195]
If the FSM defines multiple choice states connected to each other, only the first one is evaluated and the FSM gets stuck on pseudo state without the possibility of being progressed. Please see attached  test case.

[spring-statemachine-bug.zip](https://github.com/spring-projects/spring-statemachine/files/216842/spring-statemachine-bug.zip)

**Comment by jvalkeal** [comment]
Oh yes, without even looking sources I don't remember making tests for these cases. Thanks for pointing it out.

**Comment by jvalkeal** [comment]
Other tests than `testErrorHandler` from bug zip now passes.
