### ISSUE TITLE
AbstractStateMachinePersister#restore looses the FSM id

### ISSUE THREAD

**Issue by aldib** [spring-projects/spring-statemachine#198]
After restoring a FSM via the `AbstractStateMachinePersister#restore`, `StateMachine#getId` is always null

**Comment by jvalkeal** [comment]
Right, while we do handle id with persist/restore I'll trust you that there is an issue. Need to check that code which gets id for `StateMachineContext` as now that I looked it more closely, it looks bit fishy. I'll add more tests to get it fail.

**Comment by jvalkeal** [comment]
@aldib Did you ever debug or check more closely where the trouble is? Was a failure based on stuff you have in those bug zip samples what you've been sending over(which I believe used in-memory) or some other real persist storage. I'm having a bit difficult time to find when this might fail.

**Comment by jvalkeal** [comment]
Added some new tests in 'StateMachinePersistTests3` shown in above commit. Something along those lines we should get a simple test case to fail. Maybe issue is not in persist/restore perse, but in an actual persist store where `StateMachineContext` is saved.

**Comment by aldib** [comment]
Hi,
It was my mistake, sorry for wasting your time. I have an implementation `StateMachinePersist` that uses [Jackson MixIn Annotations](http://wiki.fasterxml.com/JacksonMixInAnnotations) to serialise the context in JSON format. I forgot to update it when you added the id to the context so the property was never persisted in the first place. My apologies for the confusion.

**Comment by jvalkeal** [comment]
@aldib heh, that's ok. You've anyway found so many bugs that I don't really know if I should hate you or love you :)
