### ISSUE TITLE
Guard breaks with Throwable

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-statemachine#206]
If `Guard` throws error it should evaluate to false. Should catch all exceptions and throwables.

**Comment by jvalkeal** [comment]
Looks like simple `RuntimeException` from Guard didn't break machine, what was usual suspect in #205, but `Throwable` did break it.

**Comment by darknesstm** [comment]
This is really not a good solution

**Comment by libinbin880521** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
