### ISSUE TITLE
ObjectState swallows exceptions

### ISSUE THREAD

**Issue by pgifford** [spring-projects/spring-statemachine#231]
Exceptions in [ObjectState ](https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/main/java/org/springframework/statemachine/state/ObjectState.java) are logged only.  I expected that `StateMachineListener.stateMachineError` would be called with the exception. 

The exception is being thrown in an entry action. I'm checking the extended state for validity and throwing an `IllegalStateException` if the extended state is invalid for the transition to that state machine state.  The exception is being logged but the code needs to be aware of it so the user is alerted.

**Comment by pgifford** [comment]
This looks similar to #183 and they may be effectively the same.  However, while that issues says

> However at some point we should try to propagate these error into a user level error handler so that user can choose if ssm should continue its own operations. It is kinda a choice if ssm should enter internal error state or not.

...I'd just need to be notified that an error occurred.  I don't need the state machine to continue operating.

**Comment by jvalkeal** [comment]
Closing as handled in #240.
