### ISSUE TITLE
@WithStateMachine not working when created after the state machine

### ISSUE THREAD

**Issue by antonbasic** [spring-projects/spring-statemachine#232]
When using the @WithStateMachine and the corresponding annotated methods this bean HAS to be created before the state machine is created. So if a bean with @Autowired StateMachine is in package a and @WithStateMachine bean is in package b then @WithStateMachine will have no effect. This is the complete opposite of how it works when using StateMachineListenerAdapter which depends on the state machine being created.

I also asked about this at [StackOverflow](http://stackoverflow.com/questions/37971673/spring-state-machine-annotation-withstatemachine-not-working-when-created-in-wr)

**Comment by jvalkeal** [comment]
Sorry for a late answer. I need to create a test to verify this before I can come up with a fix. Was quickly peeking`StateMachineHandlerCallHelper` and it may be that caching those beans might cause this as it happens in `afterPropertiesSet()`.

**Comment by TimGuan** [comment]
I just encounter a problem when using spring state machine @WithStateMachine.
@WithStateMachine just work when I use it on inner class which defined in the class annotated by @EnableStateMachine, but when I define class in other place it seems not work. 
Here is my code: `@Configuration @EnableStateMachine public class StateMachineConfig extends EnumStateMachineConfigurerAdapter { private Logger logger = LoggerFactory.getLogger(getClass());

@Override
public void configure(StateMachineStateConfigurer<States, Events> states)
    throws Exception {
    states
        .withStates()
        .initial(States.UNPAID)
        .states(EnumSet.allOf(States.class));
}

@Override
public void configure(StateMachineTransitionConfigurer<States, Events> transitions)
    throws Exception {
    transitions
        .withExternal()
        .source(States.UNPAID).target(States.WAITING_FOR_RECEIVE)
        .event(Events.PAY)
        .and()
        .withExternal()
        .source(States.WAITING_FOR_RECEIVE).target(States.DONE)
        .event(Events.RECEIVE);
}

@Override
public void configure(StateMachineConfigurationConfigurer<States, Events> config)
    throws Exception {
    config
        .withConfiguration()
        .autoStartup(true);
    //.listener(listener());
}

//
//@Bean
//public StateMachineListener<States, Events> listener() {
//    return new StateMachineListenerAdapter<States, Events>() {
//        @Override
//        public void transition(Transition<States, Events> transition) {
//            if (transition.getTarget().getId() == States.UNPAID) {
//                logger.info("UNPAID");
//                return;
//            }
//            if (transition.getSource().getId() == States.UNPAID
//                && transition.getTarget().getId() == States.WAITING_FOR_RECEIVE) {
//                logger.info("WAITING_FOR_RECEIVE");
//                return;
//            }
//            if (transition.getSource().getId() == States.WAITING_FOR_RECEIVE
//                && transition.getTarget().getId() == States.DONE) {
//                logger.info("DONE");
//                return;
//            }
//        }
//    };
//}
@WithStateMachine
public class Action {
    private Logger logger = LoggerFactory.getLogger(getClass());

    @OnTransition(target = "UNPAID")
    public void create() {
        logger.info("UNPAID");
    }

    @OnTransition(source = "UNPAID", target = "WAITING_FOR_RECEIVE")
    public void pay() {
        logger.info("WAITING_FOR_RECEIVE");
    }

    @OnTransition(source = "WAITING_FOR_RECEIVE", target = "DONE")
    public void receive() {
        logger.info("DONE");
    }
}
}`
but when I define Action in another class file, it is not work. 
My pom 
<dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-core</artifactId>
                <version>4.3.3.RELEASE</version>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-messaging</artifactId>
                <version>1.2.3.RELEASE</version>
            </dependency>

**Comment by renfj2006** [comment]
https://stackoverflow.com/questions/43393236/spring-state-machine-annotation-withstatemachine-not-working
