### ISSUE TITLE
StateMachine creation handle puzzle 

### ISSUE THREAD

**Issue by bwzhang2011** [spring-projects/spring-statemachine#234]
@jvalkeal, for the project sample order shipping, I noticed that it used the local cache to store the statemachine instance according to the business id like user with order id as the key. but in real world,
the project would create a lot of statemachines according to different business id like user with order, but I also noticed that the statemachine persister provide the ability for persist and restore. so I wondered which was the best way for creation, as for other samples, the statemachine would be injected during the container started to work.

further more, we could make the order subordered like the relationship between mother and son, so the parent  order could be divided into several sub orders.  as the introduction above, I first create the statemachine according to the parent order but when I did other step, I re-produced the sub order that I should create N sub-order statemachines for order tracking.  so I wander that how could I produce them, as it should inherit the context from parent-order but it should have new contextobject tag like new sub-order info.

so would you mind leaving me more message for the statemachine creation or management ? how could I make balance with such

**Comment by jvalkeal** [comment]
Eventservice sample is using pooling not to [StateMachineConfig](https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-samples/eventservice/src/main/java/demo/eventservice/StateMachineConfig.java) create too many machines. Trouble with machine which uses i.e. timers needs to be running for anything to happen. It is something what I'd like to tackle in future releases(keeping millions of machines in a persisted storage and waking up those automatically).

For sub-orders you are limited what we can currently do with parallel regions which are not easiest features to use. Ultimately what I'd like to have is a full uml submachine support #121 which would probably make these things easier.

I could try to think about this as, afaik, it's pretty common use case.

**Comment by bwzhang2011** [comment]
@jvalkeal, thanks for feed back. looking forward to next version or more features or examples provided towards such cases.

**Comment by bwzhang2011** [comment]
@jvalkeal, any update with such issue ?  spring state machine project seems not updated recently. maybe more example provided would be much better.

**Comment by jvalkeal** [comment]
@bwzhang2011 sorry for a long delay, I've been so busy with other spring projects. I've started work on #121(I have first take on it in PR review) which hopefully makes your use cases easier to implement. When we get closer to merge that feature I'll try to make a new sample around things you asked.

**Comment by bwzhang2011** [comment]
@jvalkeal, thanks for feed back and expect such nice feature brought in the future. what's more, maybe it's better submit more PRs for some idea that S.S.M could be take into consideration afterwards like follows:
1. How could I dynamic support for state machine built up manually as the configuration most would be driven by some humanity configuration like some business procedures defined. and in real world, such would be added or modified which would impact the construction of state machine creation. maybe in most cases, we would add mor modify the transition so we should think about  the dynamic support as we could not impact the schedule of the current state machine.
   
2. As S.S.M could support a lot of machines through storage way but how could I monitor that, is there any way for us to collect the current state machine info and let it be shown outside e.g some JMX integration or with ZABBIX. for each transition between states could be monitored under some temporal effectiveness condition that we cared for.
   
3. As S.S.M provides us with the distributed state machine support integrated with zookeeper, but for the persister way implementation it could not directly support the common context object like pure string id like orderSn but StatD instead. so how could I not only gain the support for distribute state machine but also enjoy the benefit from redis way. and once a machine dropped down, the other would be operated as usual as it latest state would be notified and watched and still could be recovered from the storage.

**Comment by bwzhang2011** [comment]
@jvalkeal, any update with such issue ? would you mind leaving us more info if you could spare your time ?

**Comment by jvalkeal** [comment]
I think to transfer your humanity config into a machine config could be done via `StateMachineModelFactory` which is what `UmlStateMachineModelFactory` relies on. It is rather low level api but meant for 3rd party integrations as uml xml is. Maybe you could think if your use case is generic enough to be added to project itself.

Monitoring api has been something in my mind together with auditing api(kinda similarly what spring data has). We don't want to add too much high level features over monitoring but add enough stuff so that user could easily integrate with i.e. Boot's actuator endpoints(which then exposing stuff via http/jmx).

I really haven't used any time to look distributed machine beyond zookeeper. Not sure if you wanted to use redis instead of zk but anything in dist machine gets extremely complex.

**Comment by bwzhang2011** [comment]
@jvalkeal, thanks for you feed back.  from your reply, I've had to make them more clearly that we could come to grasp the same mind as follows:
First, I admitted that StateMachineModelFactory was the way for integration with humanity config but my focus point was the modification from the humanity config either new config added or current config modified would result in the stateMachineModelFactory changing, e.g  more transitions for definition added or modified so that we had to restart the construction of the factory as there will be many machines with the S.S.M deployed it should call for any among them for restarting the factory to make sure of the construction properly according to the new factory.

Secondly, monitoring could be considered as some add-on feature for analysis e.g we could define the time period requirements during the state transition between each other, if no monitor feature provided we have to record the record with the time period promise for calculation to make sure whether the current state transition should satisfy the promise.

Thirdly, what I wanted to know more that whether we could use zookeeper persister or redis persister working together for I was sure that only the former one could satisfy the distribute state use cases while for the former, if I want to support creating high volume state machines for persisting or restoring, we should resort to redis persister so my question was how to make the balance or could use them together. so that once some machine dropped down unexpectedly, the whole could transit to another machine without any further way for restarting the state machine. so I hope you could point out the best way to handle that.

**Comment by jvalkeal** [comment]
Lets back a little, what do you actually mean by `humanity config`, how you'd configure that? I was thinking that would be a source of your machine config and thus `StateMachineModelFactory` is pretty much only way to bring in config from external source.

**Comment by bwzhang2011** [comment]
@jvalkeal,  sorry for late response. humanity config could be any way that could be set for state machine configuration e.g from some excel way, or some definition stored in DB and the latter was the most common case. for we could provide some editor page for administrator set or modification, once new definition added or modified reflecting the changing for DB storage, it would result int the change for state machine construction as you may add more possibilities for transition or modified the state name or else.  as state machine would be built up for many machines, once the definition changed the state machine should be updated according to the modification and we didn't need to restart the node of the state machine for if we could self-reconstruct for that.

**Comment by jvalkeal** [comment]
Modifying running machine config is impossible as transition/state model is locked when machine is built, but you probably didn't mean that. Lets say that this humanity config is based on uml xml and editor is papyrus. While this xml file is currently loaded from a classpath(usually package with app) I don't see that much trouble for it to be stored in some external storage where it can be modified on demand and then newly built machines(without restarting app) would be based on updated config. Was this in a nutshell what you meant?

If so I could poke around as we don't have any examples nor have I ever tried it.

**Comment by bwzhang2011** [comment]
@jvalkeal, sorry for late response too. in real world, it's better add some dynamic support for machine construction according to updated config. for the config as I referred most was a group of table data which would lead us create the state machine according to the definition e.g we could define the states which would impact the state configuration, or we could define the transitions with several table data, and most were not xml way for we would modify those data from some admin pages to CURD such. so once the data corresponded to has changed, it will call us to make it adapted to the new data to add or modify more states, add or modify or transitions those would result in the modification for the machine config.   just you could write some demo for your explanation for how to add support for the updated config through the JDBC way (I just mean the way ) and etc.

**Comment by jvalkeal** [comment]
Started to play with this and came up with this https://github.com/jvalkeal/randomstuff/tree/master/ssm-sample2. This sample is using JPA and embedded H2 DB to make code less verbose and easier to demo if you modify tables.

Had to use manual builders as it turned out that even with a factory based on normal javaconfig will create config only once. Something I need to look at as if using a model, factory could get new model every time machine is built.

**Comment by bwzhang2011** [comment]
@jvalkeal, thanks a lot for continuous support for such issue for in real world there exits many requirements that need to support out of business way. I will take a look at it and hope it could be made more dynamic building for state machine.

**Comment by jvalkeal** [comment]
Closing this for now, one resulted ticket #250 was added to todo list.
