### ISSUE TITLE
Null transition in Interceptor's postStateChange when source is a JOIN state

### ISSUE THREAD

**Issue by ItamarBenjamin** [spring-projects/spring-statemachine#235]
We have discovered that we get a null value in the transition parameter of a state machine interceptor postStateChange method. It happens only when the source state was configured with .join() on the state machine builder.

**Comment by jvalkeal** [comment]
I think I need to check this again as we're kinda in trouble with these transient pseudostates. I think actual bug here is that we may get notification transiting away from JOIN state as it really should be transition between non-pseudostates. Thanks for report, I'll try to refine how these works.

**Comment by jvalkeal** [comment]
Right this issue opened up another per #237. This null issue will be handled together with that.
