### ISSUE TITLE
Exception thrown in transition are not catch then send back to any listener

### ISSUE THREAD

**Issue by ouaibsky** [spring-projects/spring-statemachine#240]
I'm trying to understand how error are managed by statemachine.
Typical error are unchecked exception that could be raised by transition
for instance
```java
   .withExternal()
                    .source(WorkflowState.ACCEPTED)
                    .target(WorkflowState.SAVED)
                    .event(WorkflowEvent.SAVE)
                    .action(save)
                    .and()
...
    public void save(final StateContext<WorkflowState, WorkflowEvent> stateContext) {
        throw new IllegalArgumentException("Fake Error");
    }
...
``` 

In this setup I only get logger error
```
2016-08-15 15:53:05.458  WARN 18175 --- [eTaskExecutor-3] o.s.s.s.DefaultStateMachineExecutor      : Transition org.springframework.statemachine.transition.DefaultExternalTransition@76c79d7f caused error java.lang.IllegalArgumentException: Fake Error
```
looking into DefaultStateMachineExecutor.java, code accountable of that is 
```java
			try {
				transit = t.transit(stateContext);
			} catch (Exception e) {
				log.warn("Transition " + t + " caused error " + e);
			}
```

I'm expecting to be notified in such listener like StateMachineListener#stateMachineError

Is there another way to address this type of error may I suggest some code enhancement ?

Thx
Christophe

**Comment by ouaibsky** [comment]
I thing this is same issue with enter/exit action
```java
	protected ScheduledFuture<?> scheduleAction(final Action<S, E> action, final StateContext<S, E> context) {
		TaskScheduler taskScheduler = getTaskScheduler();
		if (taskScheduler == null) {
			log.error("Unable to schedule action as taskSchedule is not set, action=[" + action + "]");
			return null;
		}
		ScheduledFuture<?> future = taskScheduler.schedule(new Runnable() {

			@Override
			public void run() {
				action.execute(context);
			}
		}, new Date());
		return future;
	}
```

could be enhance as well.

I'm wondering if it's more proper to add new method
> StateMachineListener.stateMachineError
> StateMachineListener.stateMachineTransitionError
> StateMachineListener.stateMachineActionError
....

any thoughts ?

**Comment by jvalkeal** [comment]
I've been thinking thinking it a lot what would be a best way to handle errors in transitions/actions regarding how you'd react in a statemachine. Original idea of `stateMachineError` was to notify of an error machine can't recover from. Then user would know that machine cannot continue to operate.

In a yarn deployer we [catch action errors](https://github.com/spring-cloud/spring-cloud-deployer-yarn/blob/master/spring-cloud-deployer-yarn/src/main/java/org/springframework/cloud/deployer/spi/yarn/AbstractDeployerStateMachine.java#L298) and store those in extended variables to be used later. 

![tasklauncher-model](https://cloud.githubusercontent.com/assets/50398/17688745/f1e16994-6379-11e6-8d08-b45178e17097.png)

`errorGuard` then guards anonymous transition from `LAUNCHTASK` and we can react to it in a machine flow itself. I'm not saying I'm against adding more callback methods but question you need to ask yourself is what then? Does it make it easier to work with machine? If we have these callbacks and then you do something externally when transition/action error happens, you're kinda moving logic away from a machine itself. Whole point of having a statemachine is that it is self-contained and reacts to an events sent to it and as actions are user level code to be executed, shouldn't user then also handle error by themselves?

Early days of this project we just didn't have enough users to fully fine tune some of these behaviours(to suit everyone's needs) and i.e. this was left for users to raise their voices.

**Comment by ouaibsky** [comment]
Fair enough, interesting approach.

Guard it called before transition action ?

The only drawback I'm seeing right now is maybe too much boiler plate code, because I'll have to implements/set a specific error guard for each of all transdition.

In my mind guard was more "functional".

I'll try to investigate further more this option.

Christophe

**Comment by mehmetsalgar** [comment]
Actually it depends, if you really have to react every exception differently, yes, you have to define a new Guard controlling a new Transition to another State (so boiler code is inevitable).

But if you want generic handling of an error, like you get SOCKET_TIMEOUT, and the error handling should be same for whole system, then you can use Nested State Machine concept, which I discuss here, [Nested State Machine](https://mehmetsalgar.wordpress.com/2014/05/22/extremely-ajaxified-web-application-with-spring-webflow-primefaces-and-state-machines/#stateexplosion), which should reduce the boiler plate code dramatically.

Which they already implemented in Spring State Machine with [Sub State Machine](https://github.com/spring-projects/spring-statemachine/issues/121)

**Comment by ouaibsky** [comment]
Thx, interesting links

It reminds me some debates between architects  :grimacing: about error management about an internal framework we're using now and with similar concept named **SuperState**

I think this concept is really relevant but only to manage "functional state", wanted to manage **technical error/state** in the same way as **functional state** sounds confusing to me

By **functional state**, I mean something that is a meaning for an end users (or Business Analyst)

I still thinking that technical stuff should be managed in another way. This is exactly the same as for enter/exit action, you could have implemented them with state and transition.
And you didn't do it, maybe because you didn't want to see your **business state machine" polluted by technical code.

I'm thinking if it should not be better to enhance DSL like that
```java
.with...()
    .source(...)
    .guard(...)
    .action(...)
    .error(buildErrorAction())
    .and()
```

**.error** (or better name) maybe optional, with default implementation that just do same as now (log):

```java
            try {
                transit = t.transit(stateContext);
            } catch (Exception e) {
                executeErrorFunction() // of course have to catch everything and definitely log something. 
            }
```

**Comment by jvalkeal** [comment]
One reason I don't like enhancing dsl like this is that if you define config using UML XML, you don't use dsl to configure states/transitions anymore. Think we need something more generic.

**Comment by mehmetsalgar** [comment]
One big trap that you should not caught here, for State Machine only "Run-to-completion" matters, what do you want there

<code>
           try {
                transit = t.transit(stateContext);
            } catch (Exception e) {
                executeErrorFunction() // of course have to catch everything and definitely log something. 
            }
<code>

is handling your application business logic exception (can be technical also but it is your application exception) via State Machine. State Machine executed your transitions, guard, actions and reached finite state, it accomplished its duty (and you didn't received any exception caused by State Machine infrastructure) and its 'Runs-to-completion' responsibility.

In my opinion you don't want to open that sort of Pandora's box, if the exception is relevant for your application logic, then you have react to it with guard conditions or triggering another event to force the state machine to go another state (ERROR state, whatever...).

**Comment by ouaibsky** [comment]
Hi @mehmetsalgar 

> In my opinion you don't want to open that sort of Pandora's box, if the exception is relevant for your application logic, then you have react to it with guard conditions or triggering another event to force the state machine to go another state (ERROR state, whatever...).

I don't understand why it's a pandora box. Purpose of framework is to make developer's life easiest. 
I'm talking there about error which can not be recover automatically (by defining in advance a state)
I assume it something common, as an example Action that are doing network operation, file manipulation, it's pretty frequent in those case to get various unchecked exception.
In this case you get 2 options:
* As mentioned by @jvalkeal  and you, either you let developers cope with that, so back to my previous comment:
  * it assumes that all developers take care about that and thing to catch all exception then to raised the hand saying: " Ok I got unexpected exception what to do ?"
  * ActionDelegate are interesting option but I'll have to use it almost everywhere (so maybe time to find better solution), and I would like developers just providing a lambda doing the business logic with less technical code as possible.
* or you try to provide a solution for a pb that sounds recurrent. 

To pick similar need, maybe you know Rx: it's like you assume that people will manage all errors while producing items (we all know you cannot guarantee that), it's why you're subscribing with at least one lambda to consume and optionally one for error and one when stream is completed.

If I'm the only guys with this, I'll try to cope with workaround.

@jvalkeal , about UML you're right. I didn't have a look to this features (trend is more DSL 😀 )
I guest it's same issue with
```java
.with...()
    .source(...)
    .guard(...)
    .action(bizLogic lamda, onError lamda)
    .and()
```

**Comment by jvalkeal** [comment]
Adding a way to define `onError` lambda might be one solution as it'd just change what is an actual `Action

**Comment by jvalkeal** [comment]
I think what @mehmetsalgar means about _Pandora's box_ is that if you add more _non-standard_ functionalities atop of normal _run-to-completion_ model, machine core becomes more complex, you lose clear statechart representation of what machine will do and there is a bigger change that machine gets in a loop because _run-to-completion_ will never end.

**Comment by ouaibsky** [comment]
@jvalkeal, does -it mean it makes sens to provide a PR that n enhance Action with technical error mgt ?

I noted that statemachine sources is supporting java 7 (and 8 for test)
Is it plan to move main src to java 8 ?

**Comment by jvalkeal** [comment]
Yes, I'm open for PR's where `.action(bizLogic lamda, onError lamda)` or similar uses `Action` having error logic.

Plan for jdk8 only is for SSM 2.x which would rely spring framework 5.x. Haven't made any detailed plans.
