### ISSUE TITLE
Transition not accepted due to wrong comparison

### ISSUE THREAD

**Issue by glevaci** [spring-projects/spring-statemachine#253]
My team and I noticed a bug in state machine, in DefaultStateMachineExecutor class.
We were also using H2 as database for keeping list of events. Events were sent to state machine using REST. Machine is using strings for events and states. 

Java would create one instance of string "event" on location e.q. 8801, and probably Hibernate would create another instance of that string on location 8802. Those two strings are then compared by reference. Obviously, they are not equal.

Method call `machine.sendEvent(event)` would return true (event is accepted), but transition would not happen.

This is the 'guilty' method -- processTriggerQueue() method (fixed version):
`
ArrayList<Transition<S, E>> trans = new ArrayList<Transition<S, E>>();

            if (event != null) {
                ArrayList<S> ids = new ArrayList<S>(currentState.getIds());
                Collections.reverse(ids);
                for (S id : ids) {
                    for (Entry<Trigger<S, E>, Transition<S, E>> e : triggerToTransitionMap.entrySet()) {
                        Trigger<S, E> tri = e.getKey();
                        E ee = tri.getEvent();
                        Transition<S, E> tra = e.getValue();
                        // this two equals are bugfix
                        if (event.equals(ee)) {
                            if (tra.getSource().getId().equals(id) && !trans.contains(tra)) {
                                trans.add(tra);
                                continue;
                            }
                        }
                    }
                }
            }

            // most likely timer -- without bugfix, trans is empty
            if (trans.isEmpty()) {
                trans.add(triggerToTransitionMap.get(queueItem.trigger));
            }

            // go through candidates and transit max one
            handleTriggerTrans(trans, queuedMessage);
`

**Comment by jvalkeal** [comment]
Ah ok, just to be clear, did it fixed behaviour in your use case?

**Comment by glevaci** [comment]
Yes, it did. We are not sure if this == instead of .equals() would cause problems somewhere else, in some other methods.

**Comment by jvalkeal** [comment]
Think it's fine. There has been these "leftovers" from a time when we only had enums. Anyway thanks a lot for catching and tracking this. I'll try to see if I can create a test case to verify this fix.

**Comment by jvalkeal** [comment]
Ok thanks for catching this, what a dump bug it was. Put it to also get backported to 1.1.x.
