### ISSUE TITLE
StateMachineInterceptor preStateChange interceptors get called twice. 

### ISSUE THREAD

**Issue by tadgh** [spring-projects/spring-statemachine#266]
I am using an interceptor to make DB records for historical purposes, which hooks into preStateChange to do some. This is done in the same way as the Persist example. 

I noticed that I was getting duplicate DB entries, which lead me to dig into the code, and I noticed these two lines: 

[this one](https://github.com/spring-projects/spring-statemachine/blob/cc2893c4b833bb2ac60d51e7ad28e80cc40d91b8/spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java#L777)
and
[this one](https://github.com/spring-projects/spring-statemachine/blob/cc2893c4b833bb2ac60d51e7ad28e80cc40d91b8/spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java#L769)

Which seems to indicate that preStateChange will be called twice in the switchToState function. Is this intentional? Is there any way I can hook into preStateChange but only have it execute once?

**Comment by jvalkeal** [comment]
Hmm, things I do there doesn't look right(latter pre state change should bail out) now that I look it closer.

Could you give me your machine configuration and a case where you see it called twice, then I'm able to make a failing test. I believe you have choice/junction or other pseudostate in play here.

**Comment by jvalkeal** [comment]
ok, found needed info from your [SO ticket](http://stackoverflow.com/questions/40297626/statemachineinterceptor-fired-on-transient-states). Looks like there are bugs around these issues and i.e. #229 is one related. Thanks for pointing these out and I'll get these fixed.

**Comment by tadgh** [comment]
Thanks.

The issue in the SO ticket I'm not sure is the same one though. It's more about the persist recipe not working correctly with transient states, e.g. A -> x_choice -> b , but x_choice is what gets persisted, not b.

**Comment by jvalkeal** [comment]
Both of these issues looks to be caused by a same bug as persist will hook into that `preState` event in an interceptor. I was able to create a test showing it.

**Comment by jvalkeal** [comment]
I added some fixes to master(1.2.0.BUILD-SNAPSHOT). Lemmy know if those helps in any way and if so, I could backport to 1.1.x and make a release if needed.

**Comment by tadgh** [comment]
I'll pull it later today and give it a shot. Cheers

**Comment by tadgh** [comment]
This has resolved the issue of doubly-called interceptor preStateChange() hooks on the transient states. I have noticed however that when preStateChange() is called,  the Transition object still contains the transient state as its target state. The State object contains the correct "to" state, but the transition object shows the transient state when calling transition.getTarget() . Not sure if this is intentional or not.

**Comment by jvalkeal** [comment]
Right, I'll look into that.

**Comment by jvalkeal** [comment]
Yes, naturally that transition will have that transient state as a target simply because it's a real target of that transition. It's easiest to see from any real designer like papyrus where you need to always draw 2 transitions with transient states, one incoming and one outgoing.

**Comment by tadgh** [comment]
OK. In that case, there is no outgoing event fired. There is only preStateChange going from S1 -> Transient

and nothing from Transient -> S2. If this is by design, that is fine, I can work around it.
