### ISSUE TITLE
Avoid returning null for collections in AbstractState

### ISSUE THREAD

**Issue by otrosien** [spring-projects/spring-statemachine#271]
As a client I would expect an empty collection instead of null for entryActions, exitActions, stateActions, regions, triggers etc. instead of having to check for null values.

**Comment by jvalkeal** [comment]
Do you have a specific places/classes in mind, meaning what end user is facing or what we do internally in a framework? But yeah, I'm OK with this.

**Comment by jvalkeal** [comment]
Well I meant other that just `AbstractState` you mentioned in a title.

**Comment by otrosien** [comment]
Well, I was actually just stumbling over stateMachine.getState().getExitActions() returning null. So in order to make things consistent, probably all methods returning collections that are part of the State interface should be aligned.

**Comment by jvalkeal** [comment]
Sure, lets focus one thing at a time. I'll tweak things around `AbstractState` and its childs.
