### ISSUE TITLE
withExternal().timer() doesn't work

### ISSUE THREAD

**Issue by Dunnohe** [spring-projects/spring-statemachine#285]
hi, could you help to explain the difference between `withExternal()` and `withInternal()`? In my case, `withInternal().timer()` works but `withExternal().timer()` doesn't.

**Comment by jvalkeal** [comment]
Former defines `external transition` and latter `internal transition`. If timer doesn't work with external transition then it feels like a bug. What statemachine version you're using?

**Comment by jvalkeal** [comment]
Looks like timer with external transition should work. If think it's a issue, please provide a test case.

**Comment by Dunnohe** [comment]
My git repository address is git@github.com:Dunnohe/spring-statemachine-demo.git
, my git branch is feature_demo,
My statemachine configuration is In the SimpleStateMachineConfiguration class, my test class is in the TestAuto method of SimpleTransitionAppTest. Trouble you to help look, very grateful！

**Comment by jvalkeal** [comment]
You need to have a target state defined for external transition. 

```
.withExternal()
  .source(States.NOTSTART).target(States.NOTSTART).action(new Action<States, Events>() {
    @Override
      public void execute(StateContext<States, Events> context) {
        System.err.println("[code action] exec auto task");
      }
    }).timer(1000);
```
then it will exit/enter `NOTSTART` every second.

Internal transition only have source state as it will not cause state entry/exit.

Check from http://docs.spring.io/spring-statemachine/docs/1.2.0.RC1/reference/htmlsingle/#transitions what those mean.

**Comment by Dunnohe** [comment]
thanks a lot
