### ISSUE TITLE
Incorrect "EventNotAccepted" call when using sub-machine

### ISSUE THREAD

**Issue by goldenboyt** [spring-projects/spring-statemachine#287]
I have utilized UML state diagram for defining my state-machine. The problem is when using sub-machines in diagram (either in  one diagram sub-machine or sub-machine Reference) , after sending each event in sub-machine  "eventNotAccepted" method in listener is incorrectly called.

version: 1.2.0.RC1
model: [simple-submachine](https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-uml/src/test/resources/org/springframework/statemachine/uml/simple-submachine.uml)

**Comment by jvalkeal** [comment]
Maybe we can fine tune how this works as having a sub-states means that you have recursive machines handling sub-states. Getting `eventNotAccepted` is perfectly valid as those sub-machines report not accepting that event. It is possible to configure different sub-machines to handle same event conditionally and event is always offered first to most deepest active machine, then if event is not accepted, same event if offered to its super state(and to its controlling machine).

What is kinda annoying is that with `StateContext` you always get ref to root machine so these callbacks feel like redundant. I think you have a valid point here and is something what I've never really thought about until now.

**Comment by goldenboyt** [comment]
You mean that even if a sub-machine accept an event the parent state-machine also generate an "eventNotAccepted" call?

**Comment by jvalkeal** [comment]
I didn't try that yet as I briefly played with this on airplane yesterday. I'm trying to change this so that you get one message which is accurate. I don't always get these api contracts right until someone complains about it :)
