### ISSUE TITLE
Question: Terminate the scheduler thread 

### ISSUE THREAD

**Issue by goldenboyt** [spring-projects/spring-statemachine#291]
The `StateMachineConfigurationConfigurer `takes a `ConcurrentTaskScheduler `by default for scheduling times. If i have a reference to `ConcurrentTaskScheduler  `or any implementation of `TaskScheduler`, is it enough for terminating the running threads of Scheduler?

**Comment by jvalkeal** [comment]
You probably should not directly try to fiddle with those beans which are usually controlled by Spring's application context. Think this has been asked before but there are different `TaskScheduler` impls in spring which can be customised. `ConcurrentTaskScheduler` is a good default but not always a best option to use depending on a needs.

Btw, there is now gitter room for quick questions at https://gitter.im/spring-projects/spring-statemachine
