### ISSUE TITLE
@WithStateMachine not working when creating StateMachine with Factory

### ISSUE THREAD

**Issue by sanopl** [spring-projects/spring-statemachine#292]
Similar to #224 

Setting "beanName" to created StateMachine via Factory makes it work, but not when "machineId" is set in Configuration.

Tests in txt (3 files)
[fsm.txt](https://github.com/spring-projects/spring-statemachine/files/636484/fsm.txt)

**Comment by jvalkeal** [comment]
Thanks for the tests. This is an issue which has been overdue way too long. I think I'll try to get on it for `1.2.1`.

**Comment by sanopl** [comment]
I can live with that for now. I did some sort of workaround - using composite actions on state transitions.

Thanks!

**Comment by jvalkeal** [comment]
Oh, what was your workaround? I surely don't want to break your tweaks if it comes to that when I finally get my hands dirty with this one!

It's also a good time to speak out if there's something else for `@WithStateMachine`. This specific feature has always been like a drunk uncle walking on a parking lot shouting "I have a plan". Think it's time for this uncle to have his medicine refreshed :)

**Comment by jvalkeal** [comment]
Fixed in 1.2.x

**Comment by bedrin** [comment]
Awesome! Just gave it a try and it works as expected!

**Comment by jvalkeal** [comment]
ok cool. I'll see if there's anything else in a pipe for 1.2.1. I could target new release latest at early next week.
