### ISSUE TITLE
State machine not supports null state

### ISSUE THREAD

**Issue by ati90ati** [spring-projects/spring-statemachine#295]
Hello,
I have a problem with a very simple state machine.
My initial state is null and I want to go to another state.
My config looks like this:
                .withExternal()
                .source(null).target(NEW)
                .event(CREATE)
                .and()
When I try to trigger the event it fails in DefaultStateMachineExecutor.processTriggerQueue at the check of tra.getSource().getId().equals(id).
The tra.getSource().getId() will be null and the id will be also null, so are equal but failing with NullPointerException.
I don't know if it's a reason why can't use null states or it's a bug. Maybe a check can be added if both are null?
Thanks for help!
Regards,
Attila

**Comment by jvalkeal** [comment]
Initial state is required by specification so you need to have it and transition from there.

**Comment by ati90ati** [comment]
So as I understand we can't have a state machine for first time entity creation with a specific (ex. NEW) status. Only after we already set a status on it.
Thx for your answer.

**Comment by jvalkeal** [comment]
Yes, that is how state machines usually work. What comes for a states having substates(thus state is handled by its own submachine) it is possible to do controlled entry directly into specific states or use entry/exit points. However for root machine only initial state defines a state machine starts with.
