### ISSUE TITLE
Support for 'wildcard' source state in transition

### ISSUE THREAD

**Issue by tjf** [spring-projects/spring-statemachine#303]
Is there a way to have a 'wildcard' transition that will be valid from all states?

For example, if I have states 1, 2, 3, 4 and 5 -- can I configure a transition to go to state 5 based on an event, regardless of the source state?

I have looked through the code, docs and (open|closed) issues, but didn't see anything that indicated this is possible (or impossible, for that matter.)  😄 

Thanks!

**Comment by mehmetsalgar** [comment]
You have to use nested state machines for that...

Lets say you have 2 state machines SM_A and SM_B.

For SM_B you have those state s1, s2, s,3, s4, s5 and SM_A has s0. The s0 has sub state machine\nested SM_B. So you trigger event0 and you have no transition for it in SM_B but you have one in SM_A and s0, so when SM_B finds no event for event0, it will delegate to SM_A and handle the event, so transition will be valid for the all states of the SM_B.

You can see an visual example in my blog - https://mehmetsalgar.wordpress.com/2014/05/22/extremely-ajaxified-web-application-with-spring-webflow-primefaces-and-state-machines/#stateexplosion under picture 26.

**Comment by jvalkeal** [comment]
Mehmet is right as things like this should be handled with sub-machines. With configuration dsl's something this would be possible to add but i.e. uml has no notations for things like this. Is there a specific reason you'd like things like this?

**Comment by tjf** [comment]
Thanks for both of your replies.  @jvalkeal, my use case involves a workflow where a 'reset' event could return the workflow to the start.  I've used similar functionality in the [transitions](https://github.com/tyarkoni/transitions#transitioning-from-multiple-states) module available for Python.
