### ISSUE TITLE
Allow to use generic qualifiers for statemachine factory

### ISSUE THREAD

**Issue by tarioch** [spring-projects/spring-statemachine#306]
We already have generics on StateMachineConfigurerAdaptor. It should be possible to use those as qualifiers instead of having to set different names and use the string names as qualifiers.

With this we would no longer need to do
`@EnableStateMachineFactory(name="Foo")`

And use would be instead of 
```
@Autowired
@Qualifier("Foo")
private StateMachineFactory<MyState, MyEvent> myFooMachine;

@Autowired
@Qualifier("Bar")
private StateMachineFactory<MyBarState, MyBarEvent> myBarMachine;
```
it would be 
```
@Autowired
private StateMachineFactory<MyState, MyEvent> myFooMachine;

@Autowired
private StateMachineFactory<MyBarState, MyBarEvent> myBarMachine;
```
As they have different generics

**Comment by jvalkeal** [comment]
@tarioch hopefully fixed in `1.2.2.BUILD-SNAPSHOT`, give it a spin. Master build in currently ongoing.
