### ISSUE TITLE
StateMachineInterceptorList set() method does nothing

### ISSUE THREAD

**Issue by pointwisefixed** [spring-projects/spring-statemachine#318]
I believe this block of code is pretty much just clearing the argument being passed, when you actually want to clear all the interceptors in the object. Not sure if this qualifies as an Obvious Fix. But I am submitting a little PR for this.

```java
public boolean set(List<StateMachineInterceptor<S, E>> interceptors) {
		synchronized (interceptors) {
			interceptors.clear();
			return interceptors.addAll(interceptors);
		}
	}
```

**Comment by jvalkeal** [comment]
Yes, good catch. Thank's for the PR.
