### ISSUE TITLE
how to let action in synchronize execute

### ISSUE THREAD

**Issue by binlaniua** [spring-projects/spring-statemachine#352]
one request -> controller -> service -> statemachine -> sendEvent  -> response 

in response 
1. how to check the statemachine is run no error
2. how to get exception from statemachine
3. when guard return false, but sentEvent is true, how to know..

thanks

**Comment by binlaniua** [comment]
AbstractStateMachine.java

![image](https://cloud.githubusercontent.com/assets/5960462/25224525/373ae8f0-25f1-11e7-85d9-3a365c9afa07.png)

why are you not throw this exception, but only log?

**Comment by binlaniua** [comment]
found , did i same as it to write new wrapper action,

``` java
private class ExceptionCatchingAction implements Action<String, String> {

		private final Action<String, String> delegate;

		public ExceptionCatchingAction(Action<String, String> delegate) {
			Assert.notNull(delegate, "Delegate action must be set");
			this.delegate = delegate;
		}

		@Override
		public void execute(StateContext<String, String> context) {
			try {
				delegate.execute(context);
			} catch (Exception e) {
				context.getExtendedState().getVariables().put(VAR_ERROR, e);
			}
		}
	}
```

**Comment by binlaniua** [comment]
but when i use @OnTransction annotation, i found those not effect.. i read origin code found this
![image](https://cloud.githubusercontent.com/assets/5960462/25225528/43d47362-25f4-11e7-95a5-05d48acfc737.png)

just only log ...

**Comment by jvalkeal** [comment]
Could you please use StackOverflow for questions as we try to keep this as issue list.

We don't directly propagate exceptions to caller as execution is potentially executed later in different threads. User should really handle errors in actions by themselves and there are i.e. callback hooks http://docs.spring.io/spring-statemachine/docs/1.2.3.RELEASE/reference/htmlsingle/#statemachine-config-transition-actions-errorhandling.
