### ISSUE TITLE
Deadlock in lifecycle

### ISSUE THREAD

**Issue by TimGuan** [spring-projects/spring-statemachine#364]
When I've been trying to use singleton of PersistStatemache(according to the perssit demo( demo.persist.Persist)) with multiple test steps I've faced with deadlock problem. I just use the syncTaskExecutor by default and  let the thread sleep to simulate the slow processing. This is with 1.2.5.RELEASE.
```@Override
    public void configure(StateMachineConfigurationConfigurer<String, String> config)
        throws Exception {
        config
            .withConfiguration()
            .autoStartup(true);
    }
```
```@StatesOnTransition(source = States.UNPAID, target = States.WAITING_FOR_RECEIVE)
    public void pay() {
        logger.info("WAITING_FOR_RECEIVE    " +Thread.currentThread());
        try {
            Thread.sleep(3000);
            logger.info("wakeup" + "  " + Thread.currentThread());
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
```
My test case:
```
    @Test
    public void doSignals() throws InterruptedException {
        int cnt = 5;
        Thread[] threads = new Thread[cnt];
        for (int i = 0; i < cnt; i++) {
            threads[i] = new Thread(() -> {
                try {
                    persist.change(1L, "PAY");// accpet the same event  
                } catch (Exception e) {
                    e.printStackTrace();
                }
            });
        }
        for (Thread t : threads) {
            t.start();
        }
        for (Thread t : threads) {
            t.join();
        }
    }
```
jstack result:
![capture image](https://cloud.githubusercontent.com/assets/4070470/26281495/3461e7d0-3e2b-11e7-97ea-e2b4a94c8707.png)
![capture image1](https://cloud.githubusercontent.com/assets/4070470/26281496/346381bc-3e2b-11e7-8d78-1720fe9999c2.png)
By the way my spring statemachine version is 1.2.5.RELEASE

**Comment by jvalkeal** [comment]
Sigh, looks like previous fixes didn't fix all these issues.

**Comment by jvalkeal** [comment]
When you have time I've pushed some changes to 1.2.x. I removed those sync blocks as looks like those may not be needed anymore. Take it for a spin and lemmy know.

**Comment by TimGuan** [comment]
It works, thx
