### ISSUE TITLE
What's the difference between action and @OnTransition

### ISSUE THREAD

**Issue by scn7th** [spring-projects/spring-statemachine#365]
I'm confused where should I write my transition codes in spring statemachine.I found no difference in writing codes in actions during configuration or with the annotion @OnTransition. 

> Actions can be defined to be executed with transitions and states itself

, as is written in the document, **why @OnTransition is still needed?**
Would you please tell me  **the difference between action and @OnTransition**? And are they both needed to run my statemachine?

Here is where actions are commonly configured:

`@Configuration
@EnableStateMachine
public class Config51 extends EnumStateMachineConfigurerAdapter<States, Events> {

    @Override
    public void configure(StateMachineTransitionConfigurer<States, Events> transitions)
            throws Exception {
        transitions
            .withExternal()
                .source(States.S1)
                .target(States.S2)
                .event(Events.E1)
                .action(action());
    }

    @Bean
    public Action<States, Events> action() {
        return new Action<States, Events>() {

            @Override
            public void execute(StateContext<States, Events> context) {
                // do something
            }
        };
    }

}`

And @OnTransition is often used as follows:
`@WithStateMachine
public class Bean5 {

    @OnTransition(source = "S1", target = "S2")
    public void fromS1ToS2() {
    }

    @OnTransition
    public void anyTransition() {
    }
}`

Thank you!

**Comment by TimGuan** [comment]
> Application context events classes are OnTransitionStartEvent, OnTransitionEvent, OnTransitionEndEvent, OnStateExitEvent, OnStateEntryEvent, OnStateChangedEvent, OnStateMachineStart and OnStateMachineStop and others which extends base event class StateMachineEvent These can be used as is with spring typed ApplicationListener.

I think these actions are not the same as the execution time

**Comment by jvalkeal** [comment]
They are pretty much same. We just wanted to provide these annotated methods as concept is familiar from other spring umbrella projects.
