### ISSUE TITLE
PreStateChangeInterceptors are called twice for the END pseudo state

### ISSUE THREAD

**Issue by heffebaycay** [spring-projects/spring-statemachine#367]
I noticed that whenever Spring state machine transitions from one state to an END state, the PreStateChangeInterceptors are called twice in a row.

Both calls are made in `org.springframework.statemachine.support.AbstractStateMachine#switchToState`. The first one is there: 

```java
if (!isInitialTransition(transition) && !StateMachineUtils.isTransientPseudoState(state)
		&& !callPreStateChangeInterceptors(state, message, transition, stateMachine)) {
	return;
}
```
Since `PseudoStateKind.END` is not a transient pseudo state, interceptors are being called here.

The second run happens here:

```java
PseudoStateKind kind = state.getPseudoState() != null ? state.getPseudoState().getKind() : null;
if (kind != null && (kind != PseudoStateKind.INITIAL && kind != PseudoStateKind.JOIN && kind != PseudoStateKind.FORK)) {
	callPreStateChangeInterceptors(toState, message, transition, stateMachine);
}
```

`PseudoStateKind.END` is not in `INITIAL`, `JOIN`, `FORK`, so interceptors are called a second time.

You might argue that the interceptors aren't called with the same parameters. After all, the first call is using `state` and the second call is using `toState`.
The thing is, for an END pseudo state, `state` is guaranteed to be equal to `toState` (the state of kind END will be of type `DefaultPseudoState`, which makes `followLinkedPseudoStates` returns the same state). So the interceptors will actually be called twice with the same parameters.

I could provide a fix, but I'm not sure what the actual expected behavior is.

**Comment by jvalkeal** [comment]
Merged, separate backport to 1.2.x.
