### ISSUE TITLE
bean overriding conflict

### ISSUE THREAD

**Issue by wims-tijd** [spring-projects/spring-statemachine#37]
in combination with spring-security the ObjectPostProcessorConfiguration in @EnableStateMachine overrides the one from spring-security since they have the same bean name with @EnableGlobalMethodSecurity , maybe add @ConditionalOnMissingBean , since removing the ObjectPostProcessorConfiguration was sufficient

**Comment by jvalkeal** [comment]
Thanks, good catch. Can't believe this slipped through my radar.
