### ISSUE TITLE
Timer not trigger when resetStateMachine

### ISSUE THREAD

**Issue by hoswey** [spring-projects/spring-statemachine#381]
I am developing a game using spring statemachine, and want to restore the state machine from the db record;

I have checked the similar question from [The right way to reload and restart State Machine with different data set](https://stackoverflow.com/questions/38262665/the-right-way-to-reload-and-restart-state-machine-with-different-data-set)
But it seems the timer transition is not trigger when reset. Below is My code.

There are three state, the transition is timer base.
Ready(1 second) -> A (1 second)-> B.

My Question is:
**We expected when restore the state machine with state A, it will transit to the state B after one second, but it kept in the state A all the time.**

    public enum TestState {
        READY, A, B;
    }

    public void testRestore() throws Exception {

        StateMachineBuilder.Builder<TestState, Event> builder = StateMachineBuilder.builder();

        // @formatter:off
          builder.configureConfiguration()
                  .withVerifier().enabled(true)
                  .and()
            .withConfiguration()
            .taskScheduler(threadPoolTaskScheduler)
            .taskExecutor(threadPoolTaskExecutor)
            .beanFactory(applicationContext);

          builder.configureStates()
            .withStates()
            .initial(TestState.READY)
                  .states(new HashSet<>(Arrays.asList(TestState.values())));

            builder.configureTransitions()
            .withExternal()
            .source(TestState.READY).target(TestState.A)
            .timerOnce(1000)
            .and()
            .withExternal()
            .source(TestState.A).target(TestState.B)
            .timerOnce(1000);

        // @formatter:on

        StateMachine<TestState, Event> stateMachine = builder.build();
        stateMachine.addStateListener(new StateMachineListenerAdapter<TestState, Event>() {

            @Override
            public void stateChanged(org.springframework.statemachine.state.State<TestState, Event> from,
                    org.springframework.statemachine.state.State<TestState, Event> to) {

                log.info("[Testcmd=stateChanged,from={}, to={}]", from.getId(), to.getId());
            }
        });
        stateMachine.stop();
        stateMachine.getStateMachineAccessor()
                .doWithAllRegions(new StateMachineFunction<StateMachineAccess<TestState, Event>>() {
                    @Override
                    public void apply(StateMachineAccess<TestState, Event> function) {
                        function.resetStateMachine(
                                new DefaultStateMachineContext<TestState, Event>(TestState.A, null, null, null));

                    }
                });

        stateMachine.start();

        Thread.sleep(1000);
        log.info("Test, Current State is {}",stateMachine.getState().getId());
        synchronized (this) {
            wait();
        }

    }

**Comment by jvalkeal** [comment]
Ah yeah, I think this is caused because timer(timerOnce) is created when state is entered. When machine is reset, state is not entered thus timer doesn't activate. We need to create some kind of hook to this.

**Comment by hoswey** [comment]
Is there any work around to reset the state and trigger the timer as we want to restore the state machine from the persistent.

**Comment by jvalkeal** [comment]
I'm not sure. Basically scheduling works by arming/disarming triggers when state is entered/exited. 
[AbstractState](https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/main/java/org/springframework/statemachine/state/AbstractState.java#L210)
I haven't tried but in theory you get states `StateMachine.getStates()`, find a one matching id you resetting with and then casting that state to `AbstractState` to call `getTriggers()` and arming those.

**Comment by jvalkeal** [comment]
I'm trying to sneak this in to a next release as I have a concept working. Just need to figure out some corner cases but it's just basically arming those triggers for active state(s) which are restored.

**Comment by jvalkeal** [comment]
Merged per https://github.com/spring-projects/spring-statemachine/commit/66c1a532abb74660c08179606d8968a7d2848717

**Comment by jvalkeal** [comment]
Wrong commit message, going to hard reset this branch.
