### ISSUE TITLE
resetStateMachine does not clear machine id relating to prior state context

### ISSUE THREAD

**Issue by pjmoore92** [spring-projects/spring-statemachine#390]
In AbstractStateMachine.java the resetStateMachine method does not clear all machine fields upon being called with a null context (ie a new instance of StateContext to run in the machine).

Observations are that only currentState and extendedState are updated / cleared as part of the operation, I'd suggest that clearing the machine id should be included here to avoid accidentally using a stale id which refers to a context that is no longer loaded in the machine, but it may make sense to clear our other member fields also.

(I say set to null as I'm not sure it's the correct place to accept a new ID as part of method signature along with the context, but it might be a useful option)

[Link to class](https://github.com/spring-projects/spring-statemachine/blob/1.2.5.RELEASE/spring-statemachine-core/src/main/java/org/springframework/statemachine/support/AbstractStateMachine.java#L591)

**Comment by jvalkeal** [comment]
Yes, I'm going to set it to null as it's a user level field and it's null by default.

**Comment by jvalkeal** [comment]
Merged per https://github.com/spring-projects/spring-statemachine/commit/a9cf3e1acc0e4b84d3530dda96318213d81ce17b
