### ISSUE TITLE
Add reactive support

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-statemachine#397]
This is a master ticket tracking reactive implementation for upcoming 3.x series. This ticket will have many sub-issues.

Main purpose of reactive support is:
- Follow the spring5/boot2 world which heavily tries to support various reactive concepts based on reactor.
- Moving away from Spring `TaskExecutor` if favour of getting better run-to-completion model with single-thread execution based on reactor.
- Parallel execution is mostly needed in two different places, when parallels regions are uses and when state action is executed.

Epic issues:
- [x] #740 
- [x] #743 
- [x] #744 
- [x] #747 
- [x] #750 
- [x] #765 
- [x] #791 
- [x] #799
- [x] #800
- [x] #878

**Comment by jvalkeal** [comment]
I've been doing a little bit of a prototyping and having a proper reactive support means that we need to change some api's quite a bit. There's going to be breaking changes so we need to do these in a new major version.

**Comment by burakhelvaci** [comment]
You added reactive action support. Will you add reactive guard support ?

**Comment by jvalkeal** [comment]
@burakhelvaci things are very much in-progress right now, but what do you mean by reactive guard?

**Comment by jvalkeal** [comment]
Right, if you meant `ReactiveGuard` similar to `ReactiveAction`, then yes. That's not yet implemented.

**Comment by jvalkeal** [comment]
Moving this epic into `RC1` as I don't expect reactive stories to be fully handled until we've travelled through milestones.

**Comment by linux-china** [comment]
Any news for 3.0.0 release with Flux support?

**Comment by giannisapi** [comment]
Hi All, First of all great work. Any news when release 3.0.0 will be ready ?

**Comment by smartjaya** [comment]
We are looking forward to use this release, any news when 3.0.0 will be available?

**Comment by jvalkeal** [comment]
There's some documentation issue to do(which would not delay a release imho) but being honest I haven't received that much feedback about reactive features. I'm basically ready to fire a release any time.

**Comment by smartjaya** [comment]
Thank you for your response. We were trying to call a Spring Reactive Webflux endpoint in the Spring State machine, and we were not able to make the async call as they were blocking the thread. We are interested in using this release so that we can use non-blocking threads.

**Comment by jvalkeal** [comment]
Closing this as final blocking issues got fixed. There's going to be RC2, and then release.
