### ISSUE TITLE
Handle null BeanFactory in StateMachineHandlerCallHelper

### ISSUE THREAD

**Issue by java-artisan** [spring-projects/spring-statemachine#412]
I am using the StateMachineBuilder to create ad-hoc state machines. It is apparently a known issue. However, the proposed solutions don't seem to work.

```
final StateMachineBuilder.Builder<States, Events> builder = StateMachineBuilder.builder();
// doesn't work
builder.configureConfiguration().withConfiguration().beanFactory(new StaticListableBeanFactory());

// doesn't work either    
builder.configureConfiguration().withConfiguration().beanFactory(applicationContext.getAutowireCapableBeanFactory());
```
This happens regardless using a persister. Is there anything else I can try ?

System configuration:

- Linux amd64
- JDK 1.8.0_144
- Spring 4.3.11.RELEASE
- Spring SSM 1.2.6.RELEASE

**Comment by jvalkeal** [comment]
I'm finally going to take away that annoying warning message and handle that exception as this mess dates to times when we didn't have builders, thus more change of working outside of spring context.

**Comment by jvalkeal** [comment]
Merged per https://github.com/spring-projects/spring-statemachine/commit/c8062e6c6174a146faa988b95677c3d135684cc3
