### ISSUE TITLE
could the listener tell whether an event was not accepted , (OnStateNotAcceptedEvent)

### ISSUE THREAD

**Issue by wims-tijd** [spring-projects/spring-statemachine#43]

**Comment by jvalkeal** [comment]
I think this is doable when we sort out #44. Probably need to add a filter of some sort to listener event handlers so that we don't get into trouble with too many events(may be a problem with app context events).

**Comment by jvalkeal** [comment]
Paging @wims-tijd, lemmy know if this was what you had in mind?
