### ISSUE TITLE
StateMachineConfigurerAdapter doesn't find correct generics

### ISSUE THREAD

**Issue by tarioch** [spring-projects/spring-statemachine#454]
Very similar to #306 but now for the `@EnableStateMachineFactory` part

If I have the following

```java
@EnableStateMachineFactory(name = "Foo")
FooStateMachineConfig extends StateMachineConfigurerAdapter<FooState, FooEvent>(){
}

@EnableStateMachineFactory(name = "Bar")
BarStateMachineConfig extends StateMachineConfigurerAdapter<BarState, BarEvent>(){
}
```

The following thing works

```java
@Autowired
@Qualifier("Foo")
private StateMachineFactory<FooState, FooEvent> stateMachineFactory;
```

But would be nice if the following would work as well
```java
@Autowired
private StateMachineFactory<FooState, FooEvent> stateMachineFactory;
```

**Comment by tarioch** [comment]
Using 1.2.7.RELEASE

**Comment by jvalkeal** [comment]
Would you mind checking tests I have for these [MachineTypedTests](https://github.com/spring-projects/spring-statemachine/blob/1.2.x/spring-statemachine-core/src/test/java/org/springframework/statemachine/config/MachineTypedTests.java) what might be a difference in your case?

At least in those tests I'm able to auto-wire by types without using qualifiers.

**Comment by jvalkeal** [comment]
Hold on, maybe you should use `EnumStateMachineConfigurerAdapter<BarState, BarEvent>`. Not sure if this makes any difference but I remember seeing some weird issues with generics as plain `StateMachineConfigurerAdapter` may lose some info about a type if enums are used.

**Comment by tarioch** [comment]
Unfortunately I can't do this, as in our setup, State and Event aren't normal Java Enums.

**Comment by jvalkeal** [comment]
Being honest I'm not sure how well anything else than `String` or `Enum` works as a state identifier. Goal is to get full support for using any Objects but this has been low priority as I really haven't seen any use cases to use anything else than strings/enums.

What's your use case for using other objects?

**Comment by jvalkeal** [comment]
Hopefully minor issue to tweak, but I'd like to see what your stuff is based on as that would help testing a possible fix(otherwise I'm shooting in dark). If that's something you're not willing to show public, you can also email me(jvalkealahti@pivotal.io or my gmail).

**Comment by tarioch** [comment]
Got it now in a small example and even with using the EnumStateMachineConfigurerAdapter

```java
@Component
public class SimpleTaskApp {

    @Autowired
    private StateMachineFactory<FooState, FooEvent> fooStateMachineFactory;
    @Autowired
    private StateMachineFactory<BarState, BarEvent> barStateMachineFactory;

    public void run() throws Exception {
        StateMachine<FooState, FooEvent> fooStateMachine = fooStateMachineFactory.getStateMachine();
        fooStateMachine.start();
        System.out.println(fooStateMachine.getState());

        StateMachine<BarState, BarEvent> barStateMachine = barStateMachineFactory.getStateMachine();
        barStateMachine.start();
        System.out.println(barStateMachine.getState());
    }

}


@Configuration
@EnableStateMachineFactory
public class FooStateMachineConfig extends EnumStateMachineConfigurerAdapter<FooStateMachineConfig.FooState, FooStateMachineConfig.FooEvent> {

    public static enum FooState {
        FOO_INIT, FOO_DONE
    }

    public static enum FooEvent {
        FOO_SUBMIT
    }

    @Override
    public void configure(StateMachineStateConfigurer<FooState, FooEvent> states) throws Exception {
        states.withStates()
                .initial(FooState.FOO_INIT)
                .states(EnumSet.allOf(FooState.class));
    }

    @Override
    public void configure(StateMachineTransitionConfigurer<FooState, FooEvent> transitions) throws Exception {
        transitions
                .withExternal()
                .source(FooState.FOO_INIT).target(FooState.FOO_DONE)
                .event(FooEvent.FOO_SUBMIT);
    }

}

@Configuration
@EnableStateMachineFactory
public class BarStateMachineConfig extends EnumStateMachineConfigurerAdapter<BarStateMachineConfig.BarState, BarStateMachineConfig.BarEvent> {

    public static enum BarState {
        BAR_INIT, BAR_DONE
    }

    public static enum BarEvent {
        BAR_SUBMIT
    }

    @Override
    public void configure(StateMachineStateConfigurer<BarState, BarEvent> states) throws Exception {
        states.withStates()
                .initial(BarState.BAR_INIT)
                .states(EnumSet.allOf(BarState.class));
    }

    @Override
    public void configure(StateMachineTransitionConfigurer<BarState, BarEvent> transitions) throws Exception {
        transitions
                .withExternal()
                .source(BarState.BAR_INIT).target(BarState.BAR_DONE)
                .event(BarEvent.BAR_SUBMIT);
    }

}
```

This runs but prints out
```
ObjectState [getIds()=[FOO_INIT], getClass()=class org.springframework.statemachine.state.ObjectState, hashCode()=1961176822, toString()=AbstractState [id=FOO_INIT, pseudoState=org.springframework.statemachine.state.DefaultPseudoState@6ed3ccb2, deferred=[], entryActions=[], exitActions=[], stateActions=[], regions=[], submachine=null]]
ObjectState [getIds()=[FOO_INIT], getClass()=class org.springframework.statemachine.state.ObjectState, hashCode()=1016550616, toString()=AbstractState [id=FOO_INIT, pseudoState=org.springframework.statemachine.state.DefaultPseudoState@3bf7ca37, deferred=[], entryActions=[], exitActions=[], stateActions=[], regions=[], submachine=null]]
```

But I would expect the second one to be `BAR_INIT`.

I'm guessing this is because the configs don't get a unique name automatically.
If I now add unique names to each of them

```java
@EnableStateMachineFactory(name = "foo")

@EnableStateMachineFactory(name = "bar")
```

I get

```
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.springframework.statemachine.config.StateMachineFactory] is defined: expected single matching bean but found 2: bar,foo
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveNotUnique(DependencyDescriptor.java:172)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1106)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1056)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:566)
	... 14 more

```

**Comment by jvalkeal** [comment]
Yeah, bean name defaults to `stateMachineFactory` and gets overridden which is normal way in spring. Other than that this is pretty much what I have in tests, so bit weird that it fails. I'll try if I get this sample fail as well.

**Comment by jvalkeal** [comment]
Do you have a sample project showing this failure? It's something else as I didn't get these to fail.

**Comment by tarioch** [comment]
Sorry, found out in my sample project still used the old version of spring statemachine. This sample works with the new version, I'm going to try to reproduce our exact scenario in my dummy test and then update here.

**Comment by jvalkeal** [comment]
If something goes wrong with generics, then it's most likely this piece of code https://github.com/spring-projects/spring-statemachine/blob/1.2.x/spring-statemachine-core/src/main/java/org/springframework/statemachine/config/configuration/StateMachineFactoryConfiguration.java#L99.

This is simply an attempt to figure out from existing classes what are the types and pass those into bean definition and rest is then handled by spring core. If you can attach a debug break to that line or generally see what `ResolvableType` is returned for your custom stuff.

**Comment by tarioch** [comment]
Thanks, that points out the problem.

I have an own supertype in there which sits on top of StateMachineConfigurerAdapter and has some more generics arguments. Therefore the number of generics on super class is of the config is not 2. Would it be possible to go through the hierarchy until you're on the root statemachine class e.g. StateMachineConfigurer or whatever makes the most sense?

**Comment by jvalkeal** [comment]
Right ok that explains it. I probably should have done that type of search in a first place. I'll play with this a little and see how it goes.

**Comment by jvalkeal** [comment]
@tarioch ping me if that fix don't work for you.

**Comment by tarioch** [comment]
I can confirm that with 1.2.8.RELEASE this now works :)
