### ISSUE TITLE
Name JPA constraints

### ISSUE THREAD

**Issue by ghillert** [spring-projects/spring-statemachine#468]
Currently, constraints are named using random values eg: 

```
...
    alter table jpa_repository_transition_actions 
        add constraint FKhwdl9g5s5htj2jcb1xrkq6wpw 
        foreign key (actions_id) 
        references jpa_repository_action;

    alter table jpa_repository_transition_actions 
        add constraint FK6287nce3o7soy1bjdyi04heih 
        foreign key (jpa_repository_transition_id) 
        references jpa_repository_transition;
...
```

We should name *unique* and *foreign key* constraints explicitly, which will result in a nicer looking, as well as easier-to-reason-with rdbms schemas.

**Comment by jvalkeal** [comment]
Closing per https://github.com/spring-projects/spring-statemachine/commit/0f7624adebbd62f2a603e206eafbad0b5693991d
