### ISSUE TITLE
UmlModelParser wrongly sets state action with spel

### ISSUE THREAD

**Issue by ymyfrank** [spring-projects/spring-statemachine#474]
I use Papyrus neo to design state machine definition.
The language used: SPEL
After I setup a state action("Do activity"), I expected it to be executed when stay in this state.
The actual behavior is: state action not executed, unless it goes out of this state after another trigger.
I found the code, which confused me:
UmlModelParser:494, if state action language is LANGUAGE_BEAN, then put it into state actions which looks good.
UmlModelParser:503, if state action language is LANGUAGE_SPEL, then put it into state exit actions which is confusing
Can you tell if this is a bug, or a decent design for some painful reason?

**Comment by ymyfrank** [comment]
Currently I put all "state actions" into state entry actions as a work around

**Comment by jvalkeal** [comment]
Thanks for pointing it out as indeed line 503 is wrong as it should be like 494.

**Comment by jvalkeal** [comment]
Fixed in 1.2.x per https://github.com/spring-projects/spring-statemachine/commit/f524ea4f627c6bd5851eaaaeb0fcdfe2936e68aa
