### ISSUE TITLE
How to handle action error when use annotation like @OnTransition

### ISSUE THREAD

**Issue by Ethan-Zh** [spring-projects/spring-statemachine#482]
As doc says, we can handle action error like
```
       transitions
            .withExternal()
                .source(States.S1)
                .target(States.S2)
                .event(Events.E1)
                .action(action(), errorAction());
```
But when we use annotation like
```
    @OnTransition
    public void anyTransition() {
    }
```
when this function throws error, how to handle it? or the only thing I can do is  add handing error logic in every these kind of method by myself ? 
Well, what I just want is when I use annotation to config action and let me know if error throws.

**Comment by jvalkeal** [comment]
For now you need to catch that yourself as these are executed on a same level/stage as listener methods. It is sort of a side effect so there's no good ways to notify user in a same way it can be done with properly defined action.
