### ISSUE TITLE
Add hamcrest based version of expectVariable to StateMachineTestPlanBuilder

### ISSUE THREAD

**Issue by tarioch** [spring-projects/spring-statemachine#483]
It would be good to have a version of the
expectVariable() method which takes an hamcrest matcher.

So instead of

expectVariable("foo", 20) it would then be possible to do expectVariable("foo", is(greaterThan(20)))

**Comment by jvalkeal** [comment]
At a same time we could enhance all other methods as well.

**Comment by jvalkeal** [comment]
Ah bummer, need to back from a plan to add hamcrest to every method as an additional choice. Steps are based on a listener to wait something to happen in a machine which is probably reason I originally didn't support hamcrest. Comparing actual values in steps should however be possible with matchers. We probably need to overhaul whole testing infra as it is kinda old naive implementation.

**Comment by jvalkeal** [comment]
@tarioch Could you check what I did. Hopefully it is what you're looking for. We can polish and tune it until 1.2.9 is actually released.

**Comment by jvalkeal** [comment]
I was just thinking if `expectVariableMatcher` is a good method name or if we should change it to something else like `expectVariableWithMatcher` or `expectVariableWith`.

**Comment by tarioch** [comment]
I would vote for "expectVariableWith" sounds like the nicest for me. 

Another (internal) thing. Wouldn't it make sense to replace the implementation of the old expectVariable() method with a call to the new one with hasEntry()?
That way you could get rid of expectVariableKeys.

**Comment by jvalkeal** [comment]
Can't really remove anything which would break existing code what users might use. Think we can deprecate and remove when time is right.

**Comment by tarioch** [comment]
I wasn't thinking about removing, I was only thinking about changing the implementation
from a usage point of view nothing would change
But the implementation would use the same stuff.

**Comment by tarioch** [comment]
To maybe be a bit clearer, I'm thinking to have it like this:

``
		public StateMachineTestPlanStepBuilder expectVariable(Object key) {
			return expectVariableWith(IsMapContaining.hasKey(key));
		}

		public StateMachineTestPlanStepBuilder expectVariable(Object key, Object value) {
			return expectVariableWith(IsMapContaining.hasEntry(key, value));
		}
``

So the usage remains unchanged but on the implementation side you no longer need to have expectVariables

**Comment by jvalkeal** [comment]
Ah yeah that makes sense. I'll change these into what you proposed.
