### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by tavolate** [spring-projects/spring-statemachine#485]
I'm using the ssm in a web context with Spring MVC. For every request, I'm asking to the state machine factory a new state machine instance to process the request. After some request, I can see the memory growing up constantly. Is there an issue with memory releasing?

**Comment by jvalkeal** [comment]
@tavolate at least you need to stop a machine as running machine cannot end up to garbage collection. Other than that you need to provide example project showing this.

**Comment by tavolate** [comment]
I already do that. This is a snippet of my code

	@Autowired 
	private StateMachineFactory<Stato, Evento> mStateMachineFactory;

    private void handleEvent(Evento pEvent, UserEntity pUserEntity, PropostaEntity pPropostaEntity) {
		StateMachine<Stato, Evento> lStateMachine = mStateMachineFactory.getStateMachine();
		
		Stato lCurrentState = Stato.valueOf(pPropostaEntity.getStato());
		
		Message<Evento> lMessage = MessageBuilder
		.withPayload(pEvent)
		.setHeader("user", pUserEntity)
		.setHeader("entity", pPropostaEntity)
		.build();
		
		lStateMachine.stop();
		lStateMachine.getStateMachineAccessor().doWithAllRegions(pAccess -> pAccess.resetStateMachine(new DefaultStateMachineContext<Stato, Evento>(lCurrentState, null, null, null)));
		lStateMachine.start();
		
		lStateMachine.sendEvent(lMessage)
		
		lStateMachine.stop();
	}

**Comment by jvalkeal** [comment]
What you mean by `After some request`? I'd expect this to be 1000+ before jvm really need to release any memory. You should do this is a busy loop and then get some stats out from memory pools.

**Comment by jvalkeal** [comment]
Closing as didn't get more feedback. Feel free to re-open.
