### ISSUE TITLE
 Can't resolve action with id actionEnter either from registered actions nor beanfactory

### ISSUE THREAD

**Issue by zhangfk** [spring-projects/spring-statemachine#487]
I want to restore statemachine data and load machine by machineId.when I invoke stateMachineFactory.getStateMachine(machineId) then error occurred.
I debug the code found that : The default constructor of DefaultStateMachineComponentResolver's  params is empty , so when compute actions then can't get data

   Is it I use the api error or this is  a bug ? please help me ! thanks!

@Configuration
@EnableStateMachineFactory
public class StatusMachineCfg extends StateMachineConfigurerAdapter<String, String>{
	 @Resource
	 private StateRepository<JpaRepositoryState> stateRepository;
	 @Resource
     private TransitionRepository<JpaRepositoryTransition> transitionRepository;
	 @Override
	 public void configure(StateMachineModelConfigurer<String, String> model) throws Exception {
		 System.out.println("-------------------------------加载状态机-----------------------");
        model.withModel().factory(new RepositoryStateMachineModelFactory(stateRepository, transitionRepository));
    }
}

@Service
public class StatusMachineServiceImpl implements StatusMachineService{
	@Resource
	private StateRepository<JpaRepositoryState> stateRepository;
	@Resource
	private TransitionRepository<JpaRepositoryTransition> transitionRepository;
	@Resource
	private ActionRepository<JpaRepositoryAction> actionRepository;
	@Resource
	private StateMachineFactory<String, String> stateMachineFactory;
	
	@Override
	public void createMachine(MachineCfgDto data) {
		String machineId = data.getName();
		Set<String> status = new HashSet<String>(); 
		String initStatus = null;
		for(int i=0;i<data.getCfg().size();i++) {
			if(i==0) {
				initStatus =data.getCfg().get(i).getSrc();
			}
			status.add(data.getCfg().get(i).getSrc());
			status.add(data.getCfg().get(i).getTarget());
		}
		Map<String,JpaRepositoryState> machineStatus = new HashMap<String,JpaRepositoryState>();
		Set<JpaRepositoryAction> entryActions = new HashSet<JpaRepositoryAction>();
		JpaRepositoryAction entry = new JpaRepositoryAction();
		entry.setName("actionEnter");
		entryActions.add(entry);
		actionRepository.save(entryActions);
		Set<JpaRepositoryAction> exitActions = new HashSet<JpaRepositoryAction>();
		JpaRepositoryAction exit = new JpaRepositoryAction();
		exit.setName("actionExit");
		exitActions.add(exit);
		actionRepository.save(exitActions);
		for(String s : status) {
			JpaRepositoryState mStatus = stateRepository.save(new JpaRepositoryState(machineId,null,s,(initStatus.equals(s)?true:false),null,entryActions,exitActions));
			machineStatus.put(s, mStatus);
		}
		
		for(CfgData cfg : data.getCfg()) {
			JpaRepositoryTransition trans = new JpaRepositoryTransition(machineStatus.get(cfg.getSrc()),machineStatus.get(cfg.getTarget()),cfg.getEvent());
			trans.setKind(TransitionKind.EXTERNAL);
			trans.setMachineId(machineId);
			transitionRepository.save(trans);
		}
	}

	@Override
	public void submit(String machineId, String curStatus,Long[] ids) {
		StateMachine<String, String> machine = stateMachineFactory.getStateMachine(machineId);
		 PersistStateMachineHandler handler = new PersistStateMachineHandler(machine);
		 handler = new PersistStateMachineHandler(machine);
		 handler.start();
		 handler.handleEventWithState(MessageBuilder.withPayload("submit").build(),curStatus);
	}

}

**Comment by zhangfk** [comment]
I resolved it

@Configuration
@EnableStateMachineFactory
public class StatusMachineCfg extends StateMachineConfigurerAdapter<String, String>{
	 @Resource
	 private StateRepository<JpaRepositoryState> stateRepository;
	 @Resource
     private TransitionRepository<JpaRepositoryTransition> transitionRepository;
	 @Resource
	 private BeanFactory beanFactory;
	 @Override
	 public void configure(StateMachineModelConfigurer<String, String> model) throws Exception {
		 System.out.println("-------------------------------加载状态机-----------------------");
        model.withModel().factory(getFactory());
    }
	 
	 @Bean
	 public RepositoryStateMachineModelFactory getFactory() {
		 RepositoryStateMachineModelFactory ret =  new RepositoryStateMachineModelFactory(stateRepository, transitionRepository);
		 ret.setStateMachineComponentResolver(new DefaultStateMachineComponentResolver(beanFactory,null,null));
		 return ret;
	 }

}

**Comment by jvalkeal** [comment]
I assume this can be closed?
