### ISSUE TITLE
RepositoryStateMachinePersist not using contextObj as id

### ISSUE THREAD

**Issue by ractive** [spring-projects/spring-statemachine#494]
When saving a state machine with e.g. the `MongoDbRepositoryStateMachinePersist` implementation, the contextObj that is passed to the `write` method in `RepositoryStateMachinePersist` is not used at all instead of being set as the primary key or (or mongo ObjectId in this case). A default mongo objectId is therefore created and the state machine cannot be found when reading it with the `read` method (which is doing a `getRepository().findById(contextObj.toString())`).

The redis and mongo implementations use a separate field for the `@Id`, whereas the JPA impl uses the machineId as the primary key (which seems wrong).

**Comment by jvalkeal** [comment]
As PR is against master, I'll put it there are mark this as backport to 1.2.x.

**Comment by jvalkeal** [comment]
Merged
