### ISSUE TITLE
Rename spring-statemachine-boot to spring-statemachine-autoconfigure

### ISSUE THREAD

**Issue by snicoll** [spring-projects/spring-statemachine#507]
`boot` is not a proper term to describe the integration with Spring Boot.

Can you please review [this wiki page](https://github.com/spring-projects/spring-boot/wiki/Building-On-Spring-Boot) and rename this module accordingly. I can see it does things with auto-configuration and the actuator but perhaps this can be summarized  as auto-configuration?

`spring-statemachine-autoconfigure`  sounds an interesting  candidate from that perspective.

**Comment by jvalkeal** [comment]
We've used that naming in various places where `boot` stuff lives outside of boot itself. I think this is a bigger issue in a whole ecosystem how these modules are named. Some spring-cloud modules don't use any specific naming and just puts auto-config classes in any normal jar, which I've very disliked from a get-go.

But sure, we can rename this in `2.x` as it's not released.

**Comment by snicoll** [comment]
> think this is a bigger issue in a whole ecosystem how these modules are named. 

Agreed, feel free to point us to the projects where such naming is used to see if we can help fixing that.
