### ISSUE TITLE
StateMachineAnnotationPostProcessor should extract correct annotated method

### ISSUE THREAD

**Issue by omidp** [spring-projects/spring-statemachine#510]
`StateMachineAnnotationPostProcessor` should extract extract correct annotated method. This happens when annotated method also have '@Transactional' which creates additional proxy which then falsely gets added twice to a call chain. As this annotation logic were copied from SI, should follow with all fixes how it's done there currently.

Particularly I'm looking SI line [AbstractMethodAnnotationPostProcessor.java#L457](https://github.com/spring-projects/spring-integration/blob/10120cdf563ebea9f74932273f5ed616176ec7e5/spring-integration-core/src/main/java/org/springframework/integration/config/annotation/AbstractMethodAnnotationPostProcessor.java#L457) and logic in it to find exact target.

----
Original report
OnStateChanged or OnTransition runs twice after sending an event
Hi, 

I setup a simple statemachine as follow 

`transitions
            .withExternal()
                .source(States.START).target(States.GlobalEligibility).event(Events.GlobalEligibility)
                .and()
            .withExternal()
                .source(States.GlobalEligibility).target(States.DeclareService).event(Events.DeclareService)
                .and()
                .withExternal()
                .state(States.END)`

everytime I send an event ontransition or onstatechange method called twice .

sending an event 

`stateMachine.start();
        //global eligibility
        Map<String, Object> headers = new HashMap<>();
        headers.put("operation", operation);
        GenericMessage<Events> ge = new GenericMessage<Events>(Events.GlobalEligibility, headers);
        stateMachine.sendEvent(ge);
 stateMachine.stop();`

WithStateMachine Bean 

`//    @StatesOnTransition(source=States.START, target=States.GlobalEligibility)
    @StatesOnStates(source=States.START, target=States.GlobalEligibility)
    @Transactional
    public void globalEligibilityTransition(@EventHeaders Map<String, Object> headers, ExtendedState extendedState,StateContext<States, Events> stateContext, Exception e)
    {
        log.info("globalEligibilityTransition state");
}`

the above method called twice.

**Comment by jvalkeal** [comment]
Just for a ref this looks to be https://stackoverflow.com/questions/48865768/spring-statemachine-runs-unexcpectedly

**Comment by jvalkeal** [comment]
You wouldn't have a simple project to show this behaviour? I'd like to see it to replicate this behaviour.

**Comment by omidp** [comment]
I created a sample project [here](https://github.com/omidp/my-spring-boot). I realized that it has sth to do with `@Transactional` annotation.

you can see in console that eligibilityTransition log will be printed more than once.

**Comment by jvalkeal** [comment]
Indeed it has something to do with `@Transactional` which creates a proxy. Anyway thanks for reporting this as transaction should not break this like this. Lemmy play with this a little more to understand what actually happens.

**Comment by jvalkeal** [comment]
Ok, found the needed code from SI, which I copied and which need to behave same. This should get this fixed.

**Comment by omidp** [comment]
can I just check [here](https://github.com/spring-projects/spring-statemachine/blob/c2db915306b0c939bc68ebccd7f8c5401f089deb/spring-statemachine-core/src/main/java/org/springframework/statemachine/processor/StateMachineHandlerCallHelper.java#L87), if it is transactional annotation then ignore it ?

**Comment by jvalkeal** [comment]
Added some additional code which allows better checks when some further work is done. This now fixes other annotations not messing up handler processing.
