### ISSUE TITLE
Can transitions be configured as singleton

### ISSUE THREAD

**Issue by skanakas** [spring-projects/spring-statemachine#517]
I have a use case where i have to build the state machine everytime as my initial state varies time to time. 
But my transitions are static. It can be configured once and reused. Since the builder is not having any provision to inject the transitions, can we have an enhancement in the statemachine builder to inject the transitions bean. 
If yes, then can i take it up and work on it. Am in interested and have an idea to do it. 
Please let me know the possibilities.

**Comment by jvalkeal** [comment]
Don't understand what you mean by `transitions are static`. Builder pattern is pretty manual process so I don't really see what's the issue here as re-use would simply be calling a dedicated function which setups transitions.

**Comment by skanakas** [comment]
For example : 
`    public StateMachine<OBDecisionState, OBDecisionEvent> buildStateMachine(OBDecisionState currentState) throws Exception {
        Builder<OBDecisionState, OBDecisionEvent> builder = StateMachineBuilder.builder();
        try{
        	//Config
            builder.configureConfiguration()
            	.withConfiguration()
            	.beanFactory(appContext.getAutowireCapableBeanFactory())
            	.autoStartup(true)
            	.listener(stateMachineListner);

            //init state
            builder.configureStates()
                .withStates()
                .initial(currentState)
                .states(EnumSet.allOf(OBDecisionState.class));
            
            /**
             * Valid State transition
             */
            builder.configureTransitions()
            .withExternal()
            	.source(OBDecisionState.INIT)
            	.target(OBDecisionState.PENDING_DECISION)
            	.event(OBDecisionEvent.PENDING)
            	.action(appStatusChange)
            	.action(activityLogAction).and()
            .withExternal()
	            .source(OBDecisionState.INIT)
	            .target(OBDecisionState.MANUAL_REVIEW)
	            .event(OBDecisionEvent.UNDER_REVIEW)
	            .action(appStatusChange)
	            .action(activityLogAction).and()
            /**
             * Invalid State Transition       
             */
            .withInternal()
                  .source(OBDecisionState.MANUAL_REVIEW)
                  .event(OBDecisionEvent.UNDER_REVIEW)
                  .action(activityLogAction).and()                  
            .withInternal()
                  .source(OBDecisionState.APPROVED)
                  .event(OBDecisionEvent.PENDING)
                  .action(activityLogAction).and()
            .withInternal()
                  .source(OBDecisionState.APPROVED)
                  .event(OBDecisionEvent.APPROVE)
                  .action(activityLogAction).and()
        }catch(Exception e){
            throw new Exception("FAILED_TO_INSTANTIATE_STATE_MACHINE");
        }
        
        StateMachine<OBDecisionState, OBDecisionEvent> stateMachine = builder.build();
        stateMachine.getStateMachineAccessor()
        	.withRegion().addStateMachineInterceptor(interceptor);
        
        return stateMachine;
    }`

This will be instantiated for each request. Here the only initial state changes every time, but the transitions are not gonna change. 
During execution of the code, the transactions are getting build again and again, instead can I have a provision in the StateMachineBuilder to "set/inject" the StateMachineTransitionConfigurer instance. 

With this I can reuse the same instance of StateMachineTransition, instead creating it every time.

**Comment by jvalkeal** [comment]
At some point there's going to be something else available to share transition/state config but these cannot be changed due to how things work under the hood.

Looks like you are creating a new machine simply to get different starting point. Unless you have a good reason for this, it's conceptually wrong what you're trying to do. You should consider having one initial state and then having choice state to lead to state you wanna go. Also if you `restore` a machine you can set it to any state before starting it which is how machine persist works.

**Comment by skanakas** [comment]
Can you please guide me hw to make the state machine restore from a different state and can i do it for each request?

**Comment by jvalkeal** [comment]
You should go though samples. persist and eventservice are good.

**Comment by skanakas** [comment]
@jvalkeal Can you please point me to the code samples you have for this to do. 
SM persist and restore.

**Comment by skanakas** [comment]
Thanks this is resolved and hence closing it
