### ISSUE TITLE
Parallel Statemachine

### ISSUE THREAD

**Issue by xylifyx** [spring-projects/spring-statemachine#53]
I looked at spring-statemachine and its hierarchical state machines. 

What I was looking for was more like parallel state machines where the transitions are between a tuple pair of states, one state from statemachine a and one from statemachine b. Perhaps with identical state sets or different state sets. 

Then you can model eventual consistency where some tuple pairs are "rest states" where the two states corresponds in some abstract meaning and some are "volatile states" with where trigger ready transitions tries to bring it into a "rest state". 

Another advantage is that states can be changed externally, outside the control of the statemachine, and the state pair transitions will bring the system into consistency.

Is this something that is achievable with spring-statemachine.

**Comment by jvalkeal** [comment]
I don't quite get what you mean by rest/volatile states and changing state externally? Care to elaborate that a little or give an use case where you'd use these.

I'm currently adding new feature for parallel machines which would be implemented using regions. In this model state is a orthogonal composite state wrapping multiple parallel machines which optionally can be used with fork/join pseudostates.

**Comment by jvalkeal** [comment]
Let us know if you have further questions, closing now.
