### ISSUE TITLE
AbstractStatemachine#resetStateMachine resets to wrong state

### ISSUE THREAD

**Issue by chrempl** [spring-projects/spring-statemachine#554]
AbstractStatemachine#resetStateMachine restores a persisted state machine to a wrong state.

**Preconditions:** 

- hierarchical state machine
- (state machine's generic type) State is an interface
- (at least) two Enums implement State 
- Enum A contains the super-states
- Enum B contains the sub-states

**Bug:**

The "enum comparison" in AbstractStatemachine#resetStateMachine is incorrect:
```
boolean enumMatch = false;
if (state instanceof Enum && ss.getId() instanceof Enum
    && ((Enum) ss.getId()).ordinal() == ((Enum) state).ordinal()) {
    enumMatch = true;
}
```

The assumption that `state` and `ss.getId()` are member of the same Enum is not always true.

The bug is caused by the changes in Fix #537.

It affects spring-statemachine > 1.2.10.

[Project to reproduce the bug](https://github.com/chrempl/spring-statemachine-restorebug)

**Comment by jvalkeal** [comment]
Thx for sample. Yes I think these should work indeed. We never thought one might use enums like that.

**Comment by chrempl** [comment]
I take it as a compliment. We use enums like that because of shared states between different state machines. 
Will this bug be fixed in the next release? For us it's an upgrade blocker.
