### ISSUE TITLE
Actions and Guards are not invoked when creating state machine  using @EnableStateMachineFactory

### ISSUE THREAD

**Issue by rajeshhereforyou** [spring-projects/spring-statemachine#557]
Actions and Guards are not invoked when creating state machine using @EnableStateMachineFactory but both of them are working if I use @EnableStateMachine.Please suggest.

**Comment by jvalkeal** [comment]
I think you need to provide a sample or code to show what's you're asking.

**Comment by rajeshhereforyou** [comment]
Thanks for the response. Now it's working.
