### ISSUE TITLE
Fix 1.2.x build for jdk7

### ISSUE THREAD

**Issue by Jangzq** [spring-projects/spring-statemachine#561]
I saw that in Reference Documentation: Spring Statemachine 2.0.1.RELEASE is built and tested with JDK 8(all artifacts have JDK 7 compatibility) and Spring Framework 5.0.5.
However, jar in Maven repository is not compiled into JDK7 compatible binary files. Our project can only use jdk7, How do I use it?

**Comment by jvalkeal** [comment]
Ah I've forget to polish docs for that particular clause for 2.x. As 2.x build atop of framework 5 and boot 2, there's no JDK7 support anymore. If you need JDK7, you need to use 1.2.x versions.

**Comment by Jangzq** [comment]
thanks! but
in 1.2.11:

Exception in thread "main" java.lang.NoSuchMethodError: java.util.List.sort(Ljava/util/Comparator;)V
	at org.springframework.statemachine.support.DefaultStateMachineExecutor.<init>(DefaultStateMachineExecutor.java:136)

List.sort is introduced in jdk8.

**Comment by jvalkeal** [comment]
Sorry for long delay, just got back from vacation.

Your right, gradle build don't complain although I always thought it would. *Sigh*, I'll try to fix this.

**Comment by jvalkeal** [comment]
Fixed in ea778f2086487a332babc417fcfd290607ca4657
