### ISSUE TITLE
StateMachineHandlerCallHelper uses BeanFactory#toString

### ISSUE THREAD

**Issue by chrempl** [spring-projects/spring-statemachine#569]
StateMachineHandlerCallHelper#setBeanFactory asserts that the passed BeanFactory is an instance of ListableBeanFactory. 

The message of Assert#state is a concatenation of an constant String and the result of BeanFactory#toString.
In case of DefaultListableBeanFactory, this has significant performance impacts. 

Fix: 
`Assert.state(beanFactory instanceof ListableBeanFactory,
				"Bean factory must be instance of ListableBeanFactory, was " + beanFactory.getClass().getName());`

**Comment by jvalkeal** [comment]
Ah ok, fair enought.
