### ISSUE TITLE
UML model factory not working with Runtime persistence

### ISSUE THREAD

**Issue by jonybuzz** [spring-projects/spring-statemachine#574]
I'm developing on SSM 2.0.1 and Spring Boot 2.
I tried to combine the functionality of reading the model from a Eclipse Papyrus project and, at the same time, persisting the machines in a DB using JPA.:

I took the working datapersist sample, added the spring-statemachine-uml dependency, and replaced the states and trasitions config for uml config:

```
@Override
public void configure(StateMachineModelConfigurer<String, String> stateMachineModel)
      throws Exception {
    stateMachineModel.withModel().factory(modelFactory());
}
@Bean
public StateMachineModelFactory<String, String> modelFactory() {
    return new UmlStateMachineModelFactory(new ClassPathResource("project.uml"));
}
```

It doesn´t persist the machine in the DB, although Hibernate logs this:

```
Hibernate: 
    select
        jpareposit0_.machine_id as machine_1_7_0_,
        jpareposit0_.state as state2_7_0_,
        jpareposit0_.state_machine_context as state_ma3_7_0_ 
    from
        state_machine jpareposit0_ 
    where
        jpareposit0_.machine_id=?
```

I don't know where it is writing or reading from but it's not the intuitive behaviour

**Comment by jvalkeal** [comment]
Could you give me your sample project showing this problem?

**Comment by jonybuzz** [comment]
Yes, here it is. With a test
https://github.com/jonybuzz/demo-ssm

**Comment by jvalkeal** [comment]
Dependencies looks wrong. You import `spring-statemachine-bom` which from `2.0.1`. Then you add dependency for `spring-statemachine-boot` from 1.2.11. In statemachine 1.2.x boot's autoconfigure module is `spring-statemachine-boot` and in 2.0.x it is `spring-statemachine-autoconfigure`.

**Comment by jonybuzz** [comment]
Sorry, I was trying different things to see the problem and forgot to delete those. I cleaned the POM but it is still not persisting the SM

**Comment by jvalkeal** [comment]
Right it looks like we should be a bit more clever when using `StateMachineModel` from your `StateMachineModelFactory` as configuration data doesn't get updated. Maybe we should try to update/merge rather than checking if `ConfigurationData` is already provided. Anyway in `UnverifiedUmlStateMachineModelFactory` it looks like persistence starts to work if you pass `null` `ConfigurationData`.

```
//return new DefaultStateMachineModel<String, String>(new ConfigurationData<String, String>(), dataHolder.getStatesData(), dataHolder.getTransitionsData());
return new DefaultStateMachineModel<String, String>(null, dataHolder.getStatesData(), dataHolder.getTransitionsData());
```

This is how default `UmlStateMachineModelFactory` does things and that's why you see other samples working.

**Comment by jonybuzz** [comment]
Thank you. That worked
