### ISSUE TITLE
Initial state wrongly entered with entry point

### ISSUE THREAD

**Issue by kartius** [spring-projects/spring-statemachine#577]
I try to use two ways for entering into substate machine: via initial state and entry state. The problem is Initial state used anyway when I go to substate machine through the entry. 

The version is : 2.0.2.RELEASE

The test code: 

        StateMachineBuilder.Builder<States, Events> builder = StateMachineBuilder.builder();
        builder.configureConfiguration()
                .withMonitoring().monitor(monitor());
        builder.configureConfiguration()
                .withConfiguration()
                .autoStartup(true)
                .listener(listener());
        builder.configureStates()
                .withStates()
                .initial(States.S1)
                .entry(States.EntryState)
                .state(States.S1)
                .state(States.S2)
                .state(States.S3)
                .and().withStates()
                .parent(States.S2)
                    .initial(States.S21)
                    .state(States.S21, init())
                    .state(States.S22)
                    .entry(States.S2Entry)
                    .exit(States.S2Exit)
                .end(States.Finish);
        builder.configureTransitions()
                .withExternal()
                .source(States.S1).target(States.S2).event(Events.E1)
                .and().withExternal()
                .source(States.S1).target(States.S2Entry).event(Events.Entry)
                .and().withExternal()
                .source(States.S22).target(States.S2Exit).event(Events.Exit)
                .and().withEntry()
                .source(States.S2Entry).target(States.S22)
                .and().withExit()
                .source(States.S2Exit).target(States.S3);
        StateMachine<States, Events> build = builder.build();
        build.sendEvent(Events.Entry);

**Comment by jvalkeal** [comment]
Bummer, you're right. Don't understand why I've missed this.
