### ISSUE TITLE
Restoring from RedisStateMachinePersister doesn't work correctly

### ISSUE THREAD

**Issue by kartius** [spring-projects/spring-statemachine#581]
I use RedisStateMachinePersister to persist and restore state machine into redis store.
My flow is:
1. Start application with state machine, change state and persist current state machine into redis
2. Stop application
3. Restart application and restore state machine from redis
4. Send event for going to next state
My expectation was the state should be changed, but actually it didn't happen.

Code:

    protected RedisStateMachinePersister<AgentStates, AgentEvents> redisStateMachinePersister() {
        return new RedisStateMachinePersister<AgentStates, AgentEvents>(stateMachinePersist());
    }

    private StateMachinePersist<AgentStates, AgentEvents, String> stateMachinePersist() {
        RedisStateMachineContextRepository<AgentStates, AgentEvents> repository =
                new RedisStateMachineContextRepository<AgentStates, AgentEvents>(new JedisConnectionFactory());
        return new RepositoryStateMachinePersist<AgentStates, AgentEvents>(repository);
    }

//to persist
...
redisStateMachinePersister().persist(stateMachine, id);
...

// to restore
...
redisStateMachinePersister().restore(stateMachine, id);
...

**Comment by jvalkeal** [comment]
I think you need to show some kind of a sample demonstrating what you are doing as there's very little you just showed.

**Comment by kartius** [comment]
Sorry, now I rechecked it, look like works now
