### ISSUE TITLE
How to create State machine Factory

### ISSUE THREAD

**Issue by kartius** [spring-projects/spring-statemachine#585]
I follow to documentation in order to create a state machine via the factory. 
I created a class:

@Configuration
@EnableStateMachineFactory
public static class Config6
    extends StateMachineConfigurerAdapter<States, Events> {

    @Override
    public void configure(StateMachineStateConfigurer<States, Events> states)
            throws Exception {
        states
            .withStates()
                .initial(States.S1)
                .end(States.SF)
                .state(State.S1)
                .state(State.S2);
    }

}

And then I try to inject my factory:

public class Bean3 {

    @Autowired
    StateMachineFactory<States, Events> factory;

    void method() {
        StateMachine<States,Events> stateMachine = factory.getStateMachine();
        stateMachine.start();
    }
}

But an instance of the factory is null.

**Comment by jvalkeal** [comment]
If `factory` is null it means there is something else going on with your setup because spring would fail if `StateMachineFactory` cannot be autowired. This means spring doesn't even try to autowire it. You need to show more of your code, not just snippets which doesn't tell whole story.

**Comment by kartius** [comment]
Thanks for reply, already found and fixed it
