### ISSUE TITLE
Persisted state machine is reset/overwritten on load 

### ISSUE THREAD

**Issue by cornelcreanga** [spring-projects/spring-statemachine#597]
Hi,

It might be the same thing with https://github.com/spring-projects/spring-statemachine/issues/593.

Demo project: https://github.com/cornelcreanga/demo-statemachine.
Run the main class first time - notice that the state machines are properly persisted.
Run the main class second time - the state machines are re-initialized, the persisted state/context is gone.

You need postgresql to run the sample - if you want to use a docker image you can use the following docker compose file. Otherwise you will need to modify application.properties accordingly.

version: '2'
services:
  db:
    image: postgres:alpine
    ports:
    - "6432:5432"
    restart: always
    environment:
      POSTGRES_DB: validator
      POSTGRES_USER: validation_user
      POSTGRES_PASSWORD: validation_pass

Thanks.

**Comment by cornelcreanga** [comment]
Note: removing  config.autoStartup(true)  seems to do trick. I'm not sure if this is by intention or is still a bug.

**Comment by cornelcreanga** [comment]
hi, any update on this?

**Comment by Milesy** [comment]
There doesn't appear to be any engagement in here, do you know if there any other sources of support @cornelcreanga ?

**Comment by jvalkeal** [comment]
Hi, sorry I totally missed these new questions. Hmm I think if autostart really fixed this issue then I'd say it's a bug as restoring machine via service should anyway do full cycle if a lifecycle. I've probably just missed this use case(thus I'm sure I never created a test for it) as it's kinda pointless to have machine with autostart if it's anyway going to get restored. I'll try to see if there's some quick fix to it as it's annoying if it breaks like this.

Was other functionality ok when you disabled autostart?

**Comment by cornelcreanga** [comment]
Yes, I haven't noticed any problem.  I'll close this issue now.
