### ISSUE TITLE
StateMachine usage question

### ISSUE THREAD

**Issue by nomadus** [spring-projects/spring-statemachine#598]
I would like to ask a usage question. We would like to have a number of workflows, where each workflow automate a particular business function. E.g. travel request, vacation request, order of some items. All these functions are simple, but we need to store the business data (e.g. order amount, who ordered etc). What would be setup of StateMachine in such case? A separate SMs with different machines? Where should we store business data? In separate schemas (we would like to use relational database)?

**Comment by jvalkeal** [comment]
Things tends to get slightly complicated in cases like this. What we ended up doing in [spring-cloud-skipper](https://github.com/spring-cloud/spring-cloud-skipper/tree/master/spring-cloud-skipper-server-core/src/main/java/org/springframework/cloud/skipper/server/statemachine) was to pass in _business data_ as event headers. Depending on a use cases these event headers are available within run-to-completion execution.

If you end up having situation where event headers are not enough(in case they are getting lost during the execution which may happen with complex machine and use of timers), then extended state variables(which are always available to actions/guards/etc) are a good choice to use. You could always just load data from a database within actions, thought some people think this is not very _statemachine_ way of doing things.

Don't try to make too much stuff in a machine itself, keep it simple and let it to run the flow. In a real life you any way need to keep other stuff in DB if machine is the one modifying a data. While you can persist a machine(and it's context with data), you should only keep data inside a machine which is relevant for machine's operation.
