### ISSUE TITLE
usage question: wait for statemachine to complete

### ISSUE THREAD

**Issue by josephnatale** [spring-projects/spring-statemachine#604]
does the framework provide the ability to enter the statemchine and run through the entire statemachine before returning control back to the calling object?    I can probably build this out myself just wondering if I've missed something in the documentation?

**Comment by jvalkeal** [comment]
On default execution is synchronous meaning sending event and processing it will block. If you switch to threaded execution, then it will not block. These are discusses in docs.

**Comment by josephnatale** [comment]
My current implementation has a call to start() then a call to sendEvent(), each state in the statemachine has an Action that calls 'sendEvent()', my hope was that calling the first sendEvent() would block until the statemachine progressed all the way through, I"ll keep poking around at the doc, thanks!

**Comment by josephnatale** [comment]
let me try to explain a little better.  What I desire is to call statemachine.sendEvent() and for the statemachine to process through each state in the statemachine prior to the orginal call to sendEvent() returning.  I'm trying to accomplish this by adding an 'action' to each state and calling statemachine.sendEvent() in each action.  here's the code:
sm configs:
`@Override
    public void configure(StateMachineStateConfigurer<States, TransitionEvents> states)
            throws Exception {
        states
            .withStates()
                .initial(States.STATE1)
                 	.state(States.STATE1, new State1Action())
                 	.state(States.STATE2, new State2Action())
                 	.state(States.STATE3, new State3Action())
        			.state(States.STATE4, new State4Action())
        			.end(States.END);
    }`

` @Override
	    public void configure(StateMachineTransitionConfigurer<States, TransitionEvents> transitions)
	            throws Exception {

		 transitions.withExternal().source(States.STATE1).target(States.STATE2).event(TransitionEvents.NEXT)
		 	.and().withExternal().source(States.STATE2).target(States.STATE3).event(TransitionEvents.NEXT)
		 	.and().withExternal().source(States.STATE2).target(States.STATE4).event(TransitionEvents.SKIP)
		 	.and().withExternal().source(States.STATE3).target(States.STATE4).event(TransitionEvents.NEXT);
		 
	    }`

controller:
`	@RequestMapping("/test")
	public ResponseData respond(@RequestParam(value="payload", defaultValue="test") String request) throws SAXException, IOException, ParsingException{
		
		
		
		
		IParser parser =  new DelimiterParser(",");
		CanonicalModel model = parser.parse(request.getBytes());
		/*
		 * TODO: look into extendedState opposed to header here
		 * 
		 * context.getExtendedState()
                .getVariables().put("mykey", "myvalue");
		 */
		Message<TransitionEvents> message = MessageBuilder.withPayload(TransitionEvents.NEXT).setHeader("payload", model).build();
		
		cleanup();
		statemachine.start();
		statemachine.sendEvent(message);
		
		if(statemachine.hasStateMachineError()){
			cleanup();
			System.out.println("error found declining");
			return new ResponseData("declined");
		}
		cleanup();
		System.out.println("no error, approving");
		return new ResponseData("approved");
	}`
Ideally what I'm looking for is to not respond to this API call until the entire statemachine has processed.  The results I'm seeing are indicating that the API call is being responded to prior to the statemachine transitioning through all the states

**Comment by hayagreevprasanna** [comment]
@josephnatale Did you managed to solve this? I have the same problem now and looking for a solution.

**Comment by josephnatale** [comment]
I've been away from this for a while but I think I did..I'll get back to you after work today

**Comment by hayagreevprasanna** [comment]
Actually the solution posted here (https://github.com/spring-projects/spring-statemachine/issues/354#issuecomment-299121905) worked for me. Thank you!!

**Comment by MohanRaju1** [comment]
@josephnatale , can you please write us what solutions worked for you.

**Comment by josephnatale** [comment]
here's how I did it, I used the setHeader method of the MessageBuilder class to pass an object not only between states but to allow the caller of the statemachine to peak into some extra data.  Each state sets the 'model.nextTransition()' to tell the statemachine where to transition next.  From there its just a loop until statemachine.isComplete returns false
`
//lets set the payload and default the first transition to next                                                          Message message = MessageBuilder                                                                           .withPayload(TransitionEvents.NEXT)                                                                                      .setHeader("payload", model)                                                                                             .build();                                                                                                                                                                                                                                     statemachine.start();                                                                                                    //lets add some logic to this to track min/man/average response time                                                     //also need to build something to consume this API very fast                                                             long startNanos = System.nanoTime();                                                                                     while(!statemachine.isComplete()){                                                                                               //send event executing the state action                                                                                  statemachine.sendEvent(message);                                                                                         //set the message with the model/nexst transition                                                                        message =  MessageBuilder                                                                                                    .withPayload(model.getNextTransition())                                                                                  .setHeader("payload", model)                                                                                             .build();                                                                                                    }                                                                                                                        long endNanos = System.nanoTime();                                                                                       averager.calculate(endNanos-startNanos);                                                                                 model.setResponseMessage(model.getResponseMessage());                                                                                                                                                                                             statemachine.stop();                                                                                                                                                                                                                      //      System.out.println(model.printTimeline());                                                                               return new ResponseData(model.getResponseMessage() + averager.toString());
`

**Comment by KendrickAng** [comment]
For anyone else that gets stuck trying to solve the same issue, since statemachine.sendEvent() is blocking by default, you can actually just send your initial event to the statemachine, and handle any subsequent events (e.g performing additional api checks, db queries) in actions. This way, you can avoid having to manually write a model like above.

This example exposes an endpoint taking a date and long, then starts a statemachine to complete each query:
```
import org.example.common.QueryKey;
import org.example.statemachine.QueryEvent;
import org.example.statemachine.QueryState;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.ResponseEntity;
import org.springframework.messaging.Message;
import org.springframework.messaging.support.MessageBuilder;
import org.springframework.statemachine.StateMachine;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;

@RestController
public class MIDStatusService {
    private static final Logger log = LoggerFactory.getLogger(MIDStatusService.class);

    @Autowired
    private QueryService queryService;

    @GetMapping("/")
    public ResponseEntity<String> handleRoot() {
        return ResponseEntity.ok().body("Hello world");
    }

    @GetMapping("/{businessDate}/{mid}")
    public ResponseEntity<String> getMIDStatus(@PathVariable(value = "businessDate") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate businessDate,
                                       @PathVariable(value = "mid") Long mid) {
        log.info("{} ----- {} ----- {}", Thread.currentThread().getName(), businessDate, mid);
        if (businessDate == null || mid == null) {
            return ResponseEntity.badRequest().body("Incorrect params format");
        }

        log.info("query service");
        log.info(queryService.toString());

        StateMachine<QueryState, QueryEvent> sm = queryService.newQuery(businessDate, mid);
        log.info("Query started");
        Message<QueryEvent> message = MessageBuilder
                .withPayload(QueryEvent.START_QUERY)
                .build();
        sm.sendEvent(message);

//        while (!sm.isComplete()) {
//            // do nothing, just wait
//            log.info("STATE MACHINE RUNNING!");
//
//            sm.sendEvent(message);
//
//            message = MessageBuilder
//                    .withPayload(nextEvent)
//                    .build();
//        }
        String report = sm.getExtendedState().get(QueryKey.REPORT, String.class);
        log.info("FINAL REPORT: {}", report);
        return ResponseEntity.ok().body(report);
    }
}
```

State machine config:
```
package org.example.statemachine;

import org.example.common.QueryKey;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Configuration;
import org.springframework.statemachine.StateContext;
import org.springframework.statemachine.action.Action;
import org.springframework.statemachine.config.EnableStateMachineFactory;
import org.springframework.statemachine.config.EnumStateMachineConfigurerAdapter;
import org.springframework.statemachine.config.builders.StateMachineConfigurationConfigurer;
import org.springframework.statemachine.config.builders.StateMachineStateConfigurer;
import org.springframework.statemachine.config.builders.StateMachineTransitionConfigurer;

import java.time.LocalDate;
import java.util.EnumSet;

@Configuration
@EnableStateMachineFactory
public class StateMachineConfig extends EnumStateMachineConfigurerAdapter<QueryState, QueryEvent> {
    private static final Logger log = LoggerFactory.getLogger(StateMachineConfig.class);

    @Override
    public void configure(StateMachineConfigurationConfigurer<QueryState, QueryEvent> config) throws Exception {
        StateMachineEventListener listener = new StateMachineEventListener();

        config.withConfiguration()
                .autoStartup(true) // otherwise need to call sm.start() on creation
                .listener(listener);
    }

    @Override
    public void configure(StateMachineStateConfigurer<QueryState, QueryEvent> states) throws Exception {
        states.withStates()
                .initial(QueryState.QUERY_RECEIVED, initReport())
                .states(EnumSet.allOf(QueryState.class))
                .end(QueryState.END_QUERY_SUCCESS)
                .end(QueryState.END_QUERY_FAILED);
    }

    @Override
    public void configure(StateMachineTransitionConfigurer<QueryState, QueryEvent> transitions) throws Exception {
        transitions
                .withExternal()
                .source(QueryState.QUERY_RECEIVED)
                .event(QueryEvent.START_QUERY)
                .target(QueryState.API_CHECK_MID_VERSION)
                .action(checkMIDVersion())

                .and()

                .withExternal()
                .source(QueryState.API_CHECK_MID_VERSION)
                .event(QueryEvent.MID_VERSION_UNSUPPORTED)
                .target(QueryState.END_QUERY_SUCCESS)

                .and()

                .withExternal()
                .source(QueryState.API_CHECK_MID_VERSION)
                .event(QueryEvent.MID_VERSION_SUPPORTED)
                .target(QueryState.END_QUERY_SUCCESS); // TODO change this later
    }

    public Action<QueryState, QueryEvent> initReport() {
        return stateContext -> {
            setKey(stateContext, QueryKey.BUSINESS_DATE, LocalDate.MIN);
            setKey(stateContext, QueryKey.MID, -1L);
            setKey(stateContext, QueryKey.REPORT, "default report");
            log.info("Init report action done");
        };
    }

    public Action<QueryState, QueryEvent> checkMIDVersion() {
        return stateContext -> {
            log.info("Check MID Version action done");
            // ********************************************************************************************************
            // ********************************* SEND EVENTS IN ACTIONS ******************************************
            // ********************************************************************************************************
            stateContext.getStateMachine().sendEvent(QueryEvent.MID_VERSION_SUPPORTED);
            log.info("Sent MID VERSION SUPPORTED event");
        };
    }

    public void setKey(StateContext<QueryState, QueryEvent> context, QueryKey k, Object v) {
        context.getExtendedState().getVariables().put(k, v);
    }
}
```

**Comment by josephnatale** [comment]
@KendrickAng - what version are you using? I think as of version 3.0 the framework is fully reactive, meaning the 'sendEvent()' methods you call will be scheduled tasks that run asynchronously.

**Comment by KendrickAng** [comment]
Due to some limitations I'm using an older version, 2.4.0. Wasn't aware of this in 3.0 - thanks for pointing that out

**Comment by fctg-stevendoolan** [comment]
I've been wanting the do the same, to stop and wait for the StateMachine to complete.  I'm using a `java.util.concurrent.Semaphore` here with spring-statemachine version 3.2.1.  Seems to work!
```java
Semaphore semaphore = new Semaphore(0);
stateMachine.getStateMachineAccessor().doWithAllRegions(access ->
        access.addStateMachineInterceptor(new StateMachineInterceptorAdapter<S, E>() {

            @Override
            public void postStateChange(
                    State<S, E> state, Message<E> message, Transition<S, E> transition,
                    StateMachine<S, E> stateMachine, StateMachine<S, E> rootStateMachine) {
                if (stateMachine.isComplete()) {
                    semaphore.release();
                }
            }
        }));

// Blocks and waits for the StateMachine to complete.
semaphore.acquire();
```

**Comment by stevendoolan** [comment]
I've been wanting the do the same, to stop and wait for the StateMachine to complete.  I'm using a `java.util.concurrent.Semaphore` here with spring-statemachine version 3.2.1.  Seems to work!
```java
Semaphore semaphore = new Semaphore(0);
stateMachine.getStateMachineAccessor().doWithAllRegions(access ->
        access.addStateMachineInterceptor(new StateMachineInterceptorAdapter<S, E>() {

            @Override
            public void postStateChange(
                    State<S, E> state, Message<E> message, Transition<S, E> transition,
                    StateMachine<S, E> stateMachine, StateMachine<S, E> rootStateMachine) {
                if (stateMachine.isComplete()) {
                    semaphore.release();
                }
            }
        }));

// Blocks and waits for the StateMachine to complete.
semaphore.acquire();
```
