### ISSUE TITLE
Dynamically creating state machines having custom actions on transitions and states entry and exit

### ISSUE THREAD

**Issue by rachitkumar13** [spring-projects/spring-statemachine#606]
We are trying to evaluate spring statemachine to dynamically create state machines from the UI and exporting them as xml (papyrus uml). The current framework does appear to support declaring custom actions over transitions and function calls on entry and exit of a state but I couldn't locate a proper detailed example showing how the function names get attached to the ones declared in the bean and how multiple umls can be switched dynamically to generate various statemachines using the factory.

**Comment by jvalkeal** [comment]
For different uml's you'd need to create a different configs. There is a way to build machine without using annotation based configuration, see `manual configuration` from docs. I haven't tried but this might allow you to create a wrapper function if you want some sort of easy way to just pass in xml and create a machine out from that.

Central component resolving actions and guards is `StateMachineComponentResolver` which is i.e. used with uml to define references to an actual actions/guards. `DefaultStateMachineComponentResolver` is trying to find those from existing context if given but it can also be used to register actions/guards manually. You see this logic in `AbstractStateMachineModelFactory` which is a parent class of a `UmlStateMachineModelFactory`
