### ISSUE TITLE
can I use it without spring boot

### ISSUE THREAD

**Issue by cqian59420** [spring-projects/spring-statemachine#614]
My project is using spring4 , I can't find any guide about how to use statemachine without boot, can anyone point me the road.

**Comment by jvalkeal** [comment]
You just need to use `1.2.x` series which is for framework4. For that in `spring-statemachine-boot` there's only some boot things for monitoring and spring data repository setups. Samples use boot to simplify building fatjars but generally speaking plain functionality doesn't need boot. For your non boot app just use same configs(you're probably already familiar how to work outside of boot).
