### ISSUE TITLE
Is Spring State Machine suitable at a per user level?

### ISSUE THREAD

**Issue by Sutty100** [spring-projects/spring-statemachine#616]
I have a requirement which I think is suitable for a state machine but I'm not sure if **Spring** State Machine is the best fit. Essentially our websites checkout funnel guides a user through various screens with different screens shown depending on things like user segmentation, state of a customers order, geolocation etc etc. Actions taken on each screen can impact which screen is shown next. A really simple example is attached below:
![annotation 2018-12-30 170740](https://user-images.githubusercontent.com/8058978/50549495-939ffd00-0c55-11e9-9b57-aa54d2c47fba.jpg)

Clients can post updates to the state machine application such as "user has clicked continue", the application is also listening to events raised by other systems e.g. "User has changed delivery address to new geo location" all of which can effect what screens are shown next. Clients are also getting the current state of the user from the state machine application to work out what screen should be shown next.

I'd like to model this via spring state machines however I have some concerns that this might not be the best use case.

Firstly as far as I can tell each user that begins checkout will need their own state machine. This could result in tens of thousands of state machines being created every hour.

Second each users state machine will need to be persisted e.g. into Redis with a TTL of an hour or so. There are a few use cases I think I need to handle:
**When the client wishes to perform an action or update the extended state** 
To handle this I think I need to restore the state machine context from Redis via StateMachinePersister perform an action/update the extended state, persist back to Redis and then stop the state machine.

**When the client wants to find out the users current state**
To handle this I think I need to restore the state machine from Redis, read whatever properties I need and then stop the machine.

**State machine completes**
When an action results in a users state machine entering the end state it should be purged from Redis. This should be possible by simply removing the entry in Redis for that users ID.

I'm not sure if I need to stop the state machine after persisting/reading the current state but I'm worried if I don't I could end up with thousands of state machines in memory AND persisted into Redis. With the approach of stopping the machines after persisting there should only be active state machines for in flight requests but I'm not sure if this is a sensible approach?

Finally business users are able to dynamically update the checkout funnel from a management tool. This can notify the Spring application e.g. via a messaging queue but I'm unclear if I can then reload the config of the state machine by interpreting the contents of a message? Existing in flight state machines can be purged from Redis to avoid backwards compatibility problems.

**Comment by nomadus** [comment]
Please have a look at event service sample. It showcases the answers to your questions, such as:
Can you create per user statemachines? This is achieved by persisting statemachine having id set to some prefix and a user id.
The sample also shows how to do pooling, this is when you have a fixed number of machines and you persist and restore them when needed. You have to pool your state machines as the creation of a statemachine may be an expensive operation. And yes, you have to persist the statemachine, as this is done in the memory you won't have such an expensive operation as writing to the database.

**Comment by Sutty100** [comment]
Great thanks!
