### ISSUE TITLE
How to differentiate different state machine create via factory

### ISSUE THREAD

**Issue by maheshsk28** [spring-projects/spring-statemachine#618]
Hi,

I need to create state machine per endpoints, my product manages different hardware entity. Endpoint is various hardware that is manage. We are experimenting if this can be done by spring state machine as all endpoints are identified by unique id, transition happens base on events and all endpoints have states.

I'm able to create state machine through factory but how do i send event or trigger event to specific state machine in an factory. All state machine will have common states and events.

State machine per endpoint will be created after unique id is generated for hardware that need to be managed.

Thanks

**Comment by jvalkeal** [comment]
And with factory you can request by `id` which sets its id. This is kinda how `StateMachineService` works. We used it in `spring-cloud-skipper` to build machines for different flows.

**Comment by jvalkeal** [comment]
Feel free to re-open if needed.
