### ISSUE TITLE
State Machine doesn't execute action for end state

### ISSUE THREAD

**Issue by caiorcferreira** [spring-projects/spring-statemachine#620]
I expected that the following code would print the message when S2 was entered. But it didn't happened.
```java
@Override
public void configure(StateMachineStateConfigurer<State, Event> states) throws Exception {
 states
            .withStates()
            .initial(State.S1)
            .state(State.S2, printAction(), null)
            .end(State.S2);
}

private Action printAction() {
        return new Action() {
            @Override
            public void execute(StateContext stateContext) { 
                System.out.println("ACTION ON END STATE EXECUTED");
            }
        };
}

@Override
 public void configure(StateMachineTransitionConfigurer<State, Event> transitions) throws Exception {
        transitions
            .withExternal()
                .source(State.S1)
                .target(State.S2)
                .event(Event.E1)
}
```

It is the expected behaviour? The only workaround that I found was to remove the `.end(State.S2)` configuration from the state machine.

**Comment by jvalkeal** [comment]
Not sure if there was a test for this but at least for now I added one and it seems to work.

https://github.com/spring-projects/spring-statemachine/blob/1a485e4d6977f521bf02d4542edf73c22e2b4030/spring-statemachine-core/src/test/java/org/springframework/statemachine/state/StateActionTests.java#L71-L88

Think we need a bit more info or a test case showing this error.

**Comment by jvalkeal** [comment]
Closing, feel free to re-open if needed.
