### ISSUE TITLE
DefaultStateMachineContext does not override equals

### ISSUE THREAD

**Issue by hamid646** [spring-projects/spring-statemachine#628]
As part of an `@Entity` object we have `stateMachineContext`. This Entity has `@Version` annotation that Hibernate uses to check for dirty updates and increments it if any updates. However, since `DefaultStateMachineContext` does not override `equals` (that Hibernate uses for comparison), Hibernate compare object Ids and always concludes there was an update and consequently increment the version.

**Comment by jvalkeal** [comment]
@hamid646 lemmy know if that change didn't work for ya
