### ISSUE TITLE
Exception in an action defined on a transition from Choice does not break the transition

### ISSUE THREAD

**Issue by filip-majernik** [spring-projects/spring-statemachine#629]
I have two transition going out of a Choice pseudo-state. There are action defined on the transitions. However, if the action results in an exception, this exception is silently ignored and the transition to a state still happens.

Shouldn't be the exception here thrown further out?

```
private void executeActions(Collection<Action<S, E>> actions, StateContext<S, E> context) {
	if (actions == null) {
		return;
	}
	for (Action<S, E> action : actions) {
		try {
			action.execute(context);
		} catch (Throwable t) {
			log.warn("Action execution resulted error", t);
		}
	}
}
```

**Comment by jvalkeal** [comment]
It is by design that any error from actions cannot ever stop execution. You need to handle errors manually and then i.e. do error handling states or other tweaks in a machine design.

**Comment by filip-majernik** [comment]
I think this is not true. On a transition from one state to another (without any pseudo state), if the action throws an exception, the transition to that state will not succeed. Only in the pseudo state it is not like that, i.e. see the code snippet.
