### ISSUE TITLE
Class not found: org.springframework.scheduling.TaskScheduler

### ISSUE THREAD

**Issue by Rafael-Simonelli** [spring-projects/spring-statemachine#630]
I'm trying to run a simple example with spring-statemachine, but I'm getting a ClassNotFoundException when I try to create a new StateMachineBuilder.

What package should I include to solve this? And why it's not shipped as dependency of spring-statemachine?

Thanks!

POM.XML

`<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com</groupId>
	<artifactId>testes</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<java.version>10</java.version>
		<maven.compiler.plugin.version>3.6.1</maven.compiler.plugin.version>
		<springstatemachine.version>2.0.3.RELEASE</springstatemachine.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-framework-bom</artifactId>
			<version>5.0.7.RELEASE</version>
			<type>pom</type>
		</dependency>
		<dependency>
			<groupId>org.springframework.statemachine</groupId>
			<artifactId>spring-statemachine-core</artifactId>
			<version>${springstatemachine.version}</version>
		</dependency>
	</dependencies>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${maven.compiler.plugin.version}</version>
					<configuration>
						<source>${java.version}</source>
						<target>${java.version}</target>
						<encoding>UTF-8</encoding>
						<showWarnings>true</showWarnings>
						<showDeprecation>true</showDeprecation>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>`

SprintStateMachineTest.Java

`package com.testes;

import org.springframework.statemachine.config.StateMachineBuilder;

public class SprintStateMachineTest {

	public static void main(String[] args) {
		StateMachineBuilder.Builder<String, String> builder = StateMachineBuilder.builder();
		
		try {
			builder.configureStates()
					.withStates()
					.initial("SI")
					.state("S1")
					.end("SF");
			
			builder.configureTransitions()
					.withExternal()
					.source("SI").target("S1").event("E1")
					.and().withExternal()
					.source("S1").target("SF").event("E2");
		} catch (Exception e) {
			throw new RuntimeException("Deu ruim, Markin!");
		}		 
		
		var machine = builder.build();
		
		System.out.println(machine.getState());
		
		machine.sendEvent("E1");
		
		System.out.println(machine.getState());
	}
	
}`

**Comment by jvalkeal** [comment]
It should come from compile dep `spring-statemachine-core` -> `spring-messaging` -> `spring-context`. Also your `spring-framework-bom` needs to be in `dependencyManagement`, not dependency.

**Comment by Rafael-Simonelli** [comment]
By adding the following in my POM.XML it worked just fine:

`
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
			<version>5.1.4.RELEASE</version>
		</dependency>
`

Thanks for the help!

**Comment by paulnuk** [comment]
> It should come from compile dep `spring-statemachine-core` -> `spring-messaging` -> `spring-context`. Also your `spring-framework-bom` needs to be in `dependencyManagement`, not dependency.

Spring Messaging no longer has a dependency on Spring 

> It should come from compile dep `spring-statemachine-core` -> `spring-messaging` -> `spring-context`. Also your `spring-framework-bom` needs to be in `dependencyManagement`, not dependency.

Spring messaging doesn't appear to depend on String-context, at least from 5.2.3.RELEASE.
