### ISSUE TITLE
Dynamic state machine configuration

### ISSUE THREAD

**Issue by nomadus** [spring-projects/spring-statemachine#631]
Hi,
I have a use case, where I need to have a state machine with no pre-defined states. There is only an initial state and an end state, but the states in between those states are not known until a message is received. Does the current implementation support such setup?

**Comment by jvalkeal** [comment]
No it doesn't as that would not be a statemachine anymore. Fundamental concept of a machine is that states doesn't change at runtime.

**Comment by nomadus** [comment]
If the FSM gets its configuration from the persistence store, then we could add additional states to the store, right? The only thing we have to do is re-read the configuration, which probably means that we have to restart. The question is can we do the same without restarting the state machine?

**Comment by jvalkeal** [comment]
Well you can always programmatically build a machine but you can't change a running machine. Also you can play with choice states and extended state is also way to add memory to a machine which. Extended state is usually used to overcome state explosion where you'd need to create too many states to represent your machine.

**Comment by nomadus** [comment]
Thanks for the explanation. Are there any plans to add a feature to have the running machine to re-read the new state configuration? What is restricting it? The idea is not to create an infinite number of states, as this is not going to be practical. But to have a more dynamic machine, which can re-read its configuration. From my understanding, it is too costly to restart a machine, so I thought if it is possible to change without bouncing the machine.

**Comment by sunxiuqiao** [comment]
hi，I have the same question.  Have you solved it?

**Comment by atharvmishra1999** [comment]
Can we dynamically define the initial state which keeping the transitions same ?

**Comment by chomchom69420** [comment]
Hi, I am stuck in a problem where (I think) I have to use this. Please let me know if you have found a solution for it yet.
