### ISSUE TITLE
Spring State machine Infinite loop in Action

### ISSUE THREAD

**Issue by zassyne** [spring-projects/spring-statemachine#634]
My **Spring state machine** is configured with an Action that performs IO tasks forever, through a basic while (true) loop.
I am making use of **State machine Factory**, so I have multiple ones.
The question is that what would a be clean way to guarantee that all machines's actions are taking place or at least get queued ?

I looked at the example in https://docs.spring.io/spring-statemachine/docs/1.1.0.RC1/reference/htmlsingle/#statemachine-config-commonsettings
I made a sample a config which looks like :

     config.withConfiguration()
                .autoStartup(false)
                .taskExecutor(ThreadPoolTaskExecutor().also {
                    it.corePoolSize = 7
                    it.initialize()
                })
                .taskScheduler(ConcurrentTaskScheduler(Executors.newScheduledThreadPool(7)))

For **guards** that do not take place forever (no while(true)); it seems to be working as intended, guards executions are queued and as soon as 7 of them are done, the next 7 ones are taking place and so on, **but regarding the actions that execute forever**, only 7 of them will be executing and no queuing so basically **only 7 state machine's actions are executing never more..**
How can I prevent that ? 

I thought of defining an Executor service within the Action (with the while(true)) and do submit by hand and that would introduce some challenges.. but not sure if there is a better way to achieve that ? any idea ?

**Comment by jvalkeal** [comment]
Running action forever is really not something you can not do with statemachines as it pretty much stops its execution. Actions executed with transition, entry or exit are really blocking as that's how statemachine spec works. Only action fired when state is entered can be cancelled(where you actually need to manually check interrupted status).

**Comment by jvalkeal** [comment]
But having said that I don't really understand what your trying to accomplish here? Maybe if you try to describe what you really try to accomplish rather than trying to use statemachine concepts as is for something it's not really designed to do.

**Comment by zassyne** [comment]
Yeah, it is solved now. What i did is instead of having an infinite loop within an action, i make the model of the machine itself implements the while (true)  through more states.
I had some state which its action is long-polling a server forever and i had one state for that.
In my use case i have as many machines as users, and the problem described above... but it got solved by redesigning the model so that i dont have an infinite loop in an action and now the thread pool machine config is working as expected. Thank you anyway.
