### ISSUE TITLE
Add support for @EventHeader annotation

### ISSUE THREAD

**Issue by martinsefcik** [spring-projects/spring-statemachine#638]
Could you please add support for @EventHeader annotation which will bound specific header to parameter the same way as @Header annotation is working in spring messaging ?

Or do we need statemachine specific annotations (@EventHeaders/(potencially)@EventHeader) if spring messaging has @Headers/@Header for the same purpose? Cannot be added supported for these annotations in spring statemachine project instead of introducing spring state machine specific ones?

**Comment by jvalkeal** [comment]
This should be doable and I don't really remember why I didn't originally add it as concepts were pretty much copied from SI. I believe I thought about using SI's `@Headers/@Header` but I think I originally wanted to have a different annotation not to confuse with SI's functionality although stuff is resolved from a same place.
