### ISSUE TITLE
JoinPseudoState not tracking join states correctly

### ISSUE THREAD

**Issue by hamid646** [spring-projects/spring-statemachine#684]
Upgraded to 2.1.0 especially for [619](https://github.com/spring-projects/spring-statemachine/issues/619) bug. I think it has not fixed the issue completely i.e. when it is Persist State Machine, the machine is still waiting for both end states to happen. After some debugging it points to:

```
void reset(Collection<S> ids) {
    // put pack all as normal reset
    reset();

    // remove given states to reflect correct join stage
    Iterator<List<State<S, E>>> trackIter = track.iterator();
    while(trackIter.hasNext()) {
        List<State<S, E>> list = trackIter.next();
        Iterator<State<S, E>> iterator = list.iterator();
        while(iterator.hasNext()) {
            State<S, E> next = iterator.next();
            if (ids.contains(next.getId())) {
                iterator.remove();
            }
        }
        // also remove list if it became empty
        if (list.isEmpty()) {
            trackIter.remove();
        }
    }
}
```

I think it should be implemented as:

```
void reset(Collection<S> ids) {
    // put pack all as normal reset
    reset();

    // remove given states to reflect correct join stage
    Iterator<List<State<S, E>>> trackIter = track.iterator();
    while(trackIter.hasNext()) {
        List<State<S, E>> list = trackIter.next();
        Iterator<State<S, E>> iterator = list.iterator();
        while(iterator.hasNext()) {
            State<S, E> next = iterator.next();
            if (ids.contains(next.getId())) {
                iterator.remove();
                trackIter.remove();
            }
        }
    }
}
```
if you agree with this, i can create a PR

**Comment by jvalkeal** [comment]
Did you run tests with that change? I remember this being a difficult thing to fix so I would not be surprised if I missed something. I'd really like to see a new test showing this kind of change fixing something. Or do you think this is theoretical and difficult to test?

**Comment by hamid646** [comment]
Yes,  i have tested it extensively ( the service that uses SM has more than 500 tests and they are all green after this change). I tried to create a test for it but it required a Persist SM that proved to be a very hard thing to create :)

**Comment by jvalkeal** [comment]
ok, lemmy poke around that change. I'd like to get 2.1.1.RELEASE out but I'll see if we can put this in.

**Comment by hamid646** [comment]
Thanks, that would be amazing 👍

**Comment by jvalkeal** [comment]
Do you think your configuration gets hit by this:

https://github.com/spring-projects/spring-statemachine/blob/009d8331fda66eccefa3e0982836f6b7b31af3e5/spring-statemachine-core/src/main/java/org/springframework/statemachine/config/AbstractStateMachineFactory.java#L805-L820

Then when resetting I think it's indeed wrong to remove list from main track only if it became empty. In `JoinTracker` `onComplete` will anyway remove list with a match. Do you have multiple end states as that would then explain why you ended up with that fix.

I don't remember why I added
```
				// also remove list if it became empty
				if (list.isEmpty()) {
					trackIter.remove();
				}
```
Maybe it was just a dump mistake from my part. If my analysis is correct then I can at least test `JoinPseudoStateTests` reset feature isolated.

**Comment by hamid646** [comment]
Yes it does hit here and i have multiple end states. 👍

**Comment by jvalkeal** [comment]
Nice thanks a lot finding this bug. I'll release today.
