### ISSUE TITLE
Timeout doesn't seem to be doing anything

### ISSUE THREAD

**Issue by satb** [spring-projects/spring-statemachine#685]
I am trying to set a global timeout for the statemachine. Is it possible to do? After x seconds, move the state machine to a different state. I've looked at the docs that talk about 
```
.stateDoActionPolicy(StateDoActionPolicy.IMMEDIATE_CANCEL)
.stateDoActionPolicyTimeout(1, TimeUnit.MILLISECONDS)
```
I can't say what this does. From the docs this - "would simply cancel running task immediately when state is complete."

Does it mean that if an event fires that moves the it out of the state, the action will immediately cancel? Where does the timeout fit in? Is it possible to have a global state machine timeout that  moves the state machine to a final state for example? Thanks in advance for your help and thanks a lot for all the documentation on this project.

**Comment by jvalkeal** [comment]
Those settings are meant to control how `state do` actions are cancelled if they are still running when state is exited. I believe you're looking to define timers for transitions like https://docs.spring.io/spring-statemachine/docs/2.1.1.RELEASE/reference/htmlsingle/#timertrigger.

**Comment by satb** [comment]
@jvalkeal 

This line from  you helps explains better than the one in the reference guide - "Those settings are meant to control how state do actions are cancelled if they are still running when state is exited."

One last question if I may. Is there a pattern to respond back to waiting clients? I have a little bit of a convoluted way of achieving this through rx-java where from the state machine final states I publish an event which is handled by rx-java blocking observer. However, I am trying to see if I am missing any obvious way that spring-statemachine provides out of the box.

Thank you.

**Comment by jvalkeal** [comment]
No there's no good way to respond back to client. I've had to do tricks in a client to wait some states and then check if my action somewhere added something to an extended state.
