### ISSUE TITLE
Transition to non-initial state could skip initial state

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-statemachine#71]
Currently a transition targeting any other state than initial state in a submachine will always go via initial state. UML spec is not very clear on this in terms of how this should be handled. Spec mentions that machine should always enter its initial state but this this is a bit awkward if user wants to enter directly into a state in a submachine.

There are pros/cons for both approaches, so keeping this ticket here to figure out how to fix it.

**Comment by jvalkeal** [comment]
Recent commits may allow to implement this easier with able to skip initial state when executor starts. Trying to fix with 1.0.0.M3.

**Comment by lkwg82** [comment]
The question at this point is how is testing done. Have the test always start the complete machine or can we enter in the middle of somewhere? 

I think the testing perspective is a good one to find an appropriate answer.
