### ISSUE TITLE
new API or example of existing functionality for implementing SM for persistent objects

### ISSUE THREAD

**Issue by ivan-gammel** [spring-projects/spring-statemachine#72]
Typical task in enterprise web applications is to implement order workflow, for which state machine is a perfect choice. An application persists orders in database and loads them upon external event to update the order state. However, it's unclear from the documentation, how this use case can be implemented and whether it can be implemented at all or not?

**Comment by jvalkeal** [comment]
In this context are you talking about one machine per order?

**Comment by ivan-gammel** [comment]
Yes, however it looks redundant to create new instance of machine on every request: Singleton bean that deserializes state, performs transition and serializes state can be more efficient.

Ivan Gammel
________________________________
От: Janne Valkealahti<mailto:notifications@github.com>
Отправлено: ‎03.‎06.‎2015 9:47
Кому: spring-projects/spring-statemachine<mailto:spring-statemachine@noreply.github.com>
Копия: Ivan Gammel<mailto:ivan@gammel.ru>
Тема: Re: [spring-statemachine] new API or example of existing functionality for implementing SM for persistent objects (#72)

In this context are you talking about one machine per order?

---

**Comment by jvalkeal** [comment]
How close is what OP posted on SO for what your chasing here http://stackoverflow.com/questions/30595534/persisting-restoring-current-state-in-spring-statemachine?

**Comment by ivan-gammel** [comment]
OP on SO asked exactly same question, thanks.  Issues #34 and #35 are close, but not exactly covering this use case, since there probably are multiple ways to implement these SPIs.

**Comment by jvalkeal** [comment]
I know, there's a little difference in flavour. Just trying to understand the requirement so that when we get a change to do some coding we'd leave it open for various types of requirements ;)

**Comment by jvalkeal** [comment]
Closing this, work is ongoing in #35 and #73 with some base code already. Will get finished by 1.0.0.M3.
