### ISSUE TITLE
SubMachine initial state gets called when resuming from persistence

### ISSUE THREAD

**Issue by Fenhryl** [spring-projects/spring-statemachine#725]
Hi,
I have an issue whith how the StateMachine works and not sure this is a bug or the way we use it (could be related to #71)
We use the UmlStateMachineModelFactory and a diagram made under papyrus to create the skeleton of our SM. The architecture is composed of multiple levels of subMachine (up to 3 levels so far). The machine is persisted on a Database.

At some point we enter a SubMachine and calls an entry function on state S1 that will send an asynchronous message. The machine is stopped and persisted in the next state S2.
We then receive a response to our asynchronous message, restore the machine and send an event to trigger the transition from S2 to S3. This transition works fine but right after it completed, the initial state of the SubMachine is called again, resubmitting a message, which is not what we want.
Is it a configuration problem on our side? or is it the wanted behaviour? How can we bypass this issue?
Thanks

**Comment by jvalkeal** [comment]
Would you have any kind of a test case to show this issue? There are so many places where things can go wrong so I'd really need to see a full machine configuration and how you use this in this case.

**Comment by don-vip** [comment]
I work with @Fenhryl . The use case is the same as the one behind #729. We're testing the new development version to see if it fixes this problem as well. We'll let you know.

**Comment by don-vip** [comment]
Hello,
We upgraded to 2.1.2.RELEASE and it seems this issue is fixed, probably thanks to #732 + #735.
We'll do more tests next week to be sure the issue is gone.

**Comment by Fenhryl** [comment]
Nice to hear, thx @don-vip & @jvalkeal for the quick support and answer :)
Cheers

**Comment by jvalkeal** [comment]
Good to know, most likely due to #735 as that was a cause to some odd behaviour in spring-cloud-skipper when machine was re-built from persistence.
