### ISSUE TITLE
Change StateMachineFunction to Consumer

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-statemachine#767]
`StateMachineFunction` dates back to pre jdk8 era so it's effectively `java.util.function.Consumer`. Deprecate `StateMachineFunction` and change core to support `Consumer` or `Function`.

**Comment by flycash** [comment]
The classes and functions using the StateMachineFunction are marked as @Deprecated ? I want to help to do this.

**Comment by jvalkeal** [comment]
This really means to deprecate `StateMachineFunction` in:

```
public interface StateMachineAccessor<S, E> {
  void doWithAllRegions(StateMachineFunction<StateMachineAccess<S, E>> stateMachineAccess);
  void doWithRegion(StateMachineFunction<StateMachineAccess<S, E>> stateMachineAccess);
}
```

And then add new methods taking `Consumer` as an parameter. This then allows us to drop `StateMachineFunction` in some future versions.

If you want to try this, thanks, go ahead.
