### ISSUE TITLE
NullPointerException in PseudoStates without Transitions

### ISSUE THREAD

**Issue by SchreiberLex** [spring-projects/spring-statemachine#775]
Building a statemachine with a pseudostate that has no transition throws a nested NullPointerException.
I see two options for improvment:
1. Throw a specific exception that signals the user, what is wrong (pseudostate x has no transitions defined), or 
2. build the statemachine without the affected pseudostates (might cause further issues)

**Comment by jvalkeal** [comment]
Right ok, I think this could be handled with default `StateMachineModelVerifier` impl which would then fail fast.

**Comment by jvalkeal** [comment]
Marking `3.0.0.RC1` for now but this might be something we could backport to `2.x`.
