### ISSUE TITLE
Refactor tests to use junit5

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-statemachine#779]
Move away from junit4 so that we don't need to rely on vintage.

**Comment by flycash** [comment]
I want to help to do this. I plan to remove the dependencies of junit4 and add the junit5's dependencies. And then fix all compile errors and runtime errors.
Any suggestions?

**Comment by jvalkeal** [comment]
Sure thx, I'll assign this to you. It's crazy amount of work so it's ok to do it via multiple commits. It's a clean removal of junit4 except with #780.

**Comment by jvalkeal** [comment]
Right github organization where this project is doesn't allow to actually pick assignee outside of an organization. But you have it now.

**Comment by flycash** [comment]
Okay, thanks
