### ISSUE TITLE
xml definition for the state-machine

### ISSUE THREAD

**Issue by bwzhang2011** [spring-projects/spring-statemachine#78]
sometimes we would define the state-machine transition in xml file and through the facade api to read the xml to generate the state-machine for transition listening . so it will be better with such feature under plan.

**Comment by lkwg82** [comment]
If you need that and would see that in the spring state machine, what about drawing an example and a could-be-this-kind-of-xml?

This could be discussed and evolved further.

**Comment by bwzhang2011** [comment]
@lkwg82, thanks for view and feed back. maybe it's due to the appropriate expressing for what I suggested. and of source, maybe a drawing style of some xml file could be such kind. and I know currently squirrel could provide such similar thing. please take a look at https://github.com/hekailiang/squirrel

**Comment by jvalkeal** [comment]
Idea is in table yes, but there's no concrete plans or designs. `SCXML` is one option but I'm a little unfamiliar with it and definitely it would not suit needs for our use cases. Possibly we could implement it with features it provides.

One other option is to simply provide a normal spring xml namespace which would duplicate same configuration model compared to current javaconfig. This xml option is anyway needed if/when we some day in a future get UI designer integration in IDE's.

Anyway all ideas are welcome!

**Comment by bwzhang2011** [comment]
@jvalkeal, thanks for follow such issue. the idea for xml way came out of the jbpm xml, as comparison with squirrel, support for xml way should be encouraged and the xsd could be imported and for validation also. so it could be described for complex state communication.

**Comment by mehmetsalgar** [comment]
I know this is not exactly what is asked here but I created a blog entry explaining how to convert an UML Diagram to runnable  Spring State Machine.

When we think, UML Diagram is a XMI file, men can also interpret this as create a runnable State Machine from a XML file :)

Here is the link

 https://mehmetsalgar.wordpress.com/2015/12/14/ajax-spring-web-flow-and-spring-state-machine/

**Comment by mehmetsalgar** [comment]
Well after creating the other blog about how to create Spring State Machine configuration via an UML Model, I was intrigued about to figure out how difficult would be to create a Domain Specific Language(DSL) to build Spring State Machine configuration. It seems with the Eclipse XText framework it is quite easy. If you like to configure your Spring State Machines via text file please read my new blog.

https://mehmetsalgar.wordpress.com/2016/01/20/xtext-domain-specific-language-and-spring-state-machine/

**Comment by jvalkeal** [comment]
Going to close this one as there is now xml definition via papyrus uml done in #193. Public config pojo model also allows to create additional xml impls if needed as uml integrates via that.
