### ISSUE TITLE
Question: release 2.1.3.RELEASE

### ISSUE THREAD

**Issue by hamid646** [spring-projects/spring-statemachine#783]
Hi there, all issues for milestone [2.1.3.RELEASE](https://github.com/spring-projects/spring-statemachine/milestone/52) have been fixed. is it possible for you to release it? there is fix that we really need. Thanks

**Comment by jvalkeal** [comment]
Yes, I think I might have one thing to forward port to `2.0.x` and `2.1.x`. I'll do those releases first thing start of next week.

**Comment by jvalkeal** [comment]
No `2.1.x` is ready, `2.0.x` needs #739. Anyway I'll do release latest on Monday.
