### ISSUE TITLE
multiple @EnableStateMachineFactory with different name does not work.

### ISSUE THREAD

**Issue by netalpha** [spring-projects/spring-statemachine#787]
I have two implementations of `EnumStateMachineConfigurerAdapter`: one is called `config1`, the other is called `config2`.

```
@Configuration
@EnableStateMachineFactory(name = "config1", contextEvents = false)
public class Config1 extends EnumStateMachineConfigurerAdapter<S, E> {
...
}

@Configuration
@EnableStateMachineFactory(name = "config2", contextEvents = false)
public class Config2 extends EnumStateMachineConfigurerAdapter<S, E> {
...
}
```

When I tried to get the state machine by `this.factory.getStateMachine("config1");`, it gave me the `config2` machine

**Comment by netalpha** [comment]
I have tried to use the @EnableStateMachine annotation, all 2 beans are loaded. However, I have to make its scope as `prototype`. As to the reference document, scope is not supported well I guess.

```
@Configuration
@EnableStateMachine(name = "config1", contextEvents = false)
public class Config1 extends EnumStateMachineConfigurerAdapter<S, E> {
...
}

@Configuration
@EnableStateMachine(name = "config2", contextEvents = false)
public class Config2 extends EnumStateMachineConfigurerAdapter<S, E> {
...
}
```

**Comment by netalpha** [comment]
Give you some context I want, basically, I have 2 types of customers, one type would use `config1` state machine, the other would use `config2`.  Each customer would have his state machine. I will build from the raw config, and restore via the persisted context.

**Comment by Niklisto** [comment]
`@Configuration
@EnableStateMachineFactory(name = "config1Factory", contextEvents = false)
public class Config1 extends EnumStateMachineConfigurerAdapter<S, E> {
...
}

@Configuration
@EnableStateMachineFactory(name = "config2Factory", contextEvents = false)
public class Config2 extends EnumStateMachineConfigurerAdapter<S, E> {
...
}

@Autowired
@Qualifier("config1Factory")
private StateMachineFactory<S, E> factory1;

@Autowired
@Qualifier("config2Factory")
private StateMachineFactory<S, E> factory2;

......

m1 = factory1.getStateMachine("Machine1forType1");
m2 = factory1.getStateMachine("Machine2forType1");
m3 = factory2.getStateMachine("Machine1forType2");
m4 = factory2.getStateMachine("Machine2forType2");
< use machines here >
`
