### ISSUE TITLE
Simplify configuration for statemachines outside of an application context

### ISSUE THREAD

**Issue by paulalexwilson** [spring-projects/spring-statemachine#79]
I've been able to configure a statemachine *in the absence of an application context* by manually adding executors and schedulers to the factory/statemachine however I ran out of patience when sub-statemachines also required this set up. It seems that configuration is tightly bound to Spring.

It would be great to have a way to simply set up a statemachine without an application context (or some clear documentation in case I've missed something obvious)!

**Comment by jvalkeal** [comment]
This is partly implemented in master(not in milestone 2) with #45. i.e. https://github.com/spring-projects/spring-statemachine/blob/master/spring-statemachine-core/src/test/java/org/springframework/statemachine/config/ManualBuilderTests.java is showing how it is used. Next milestone will have good support working outside of app context and normal spring `@Configuration` classes.

**Comment by jvalkeal** [comment]
Also #69 lifted requirement to use enums as states and events so it's easier to build dynamic machines outside of a context.

**Comment by paulalexwilson** [comment]
Yes I was glad to see ObjectStateMachineFactory appear on master!

**Comment by jvalkeal** [comment]
Closing. Added some docs via https://github.com/spring-projects/spring-statemachine/commit/9b6caaf6b827ee1dfefe992a29c9f59c3b86207d
