### ISSUE TITLE
Make Action execution in fork/join section concurrent

### ISSUE THREAD

**Issue by balutelD** [spring-projects/spring-statemachine#790]
Hi, is it possible to make Action execution in fork/join section concurrent? Could you please share an example

**Comment by jvalkeal** [comment]
It is, just needs to change execution like in `tasks` sample.

https://github.com/spring-projects/spring-statemachine/blob/9f10700da251e5e5b52ef6b6d614f7b83a05166e/spring-statemachine-samples/tasks/src/main/java/demo/tasks/Application.java#L200-L205
