### ISSUE TITLE
Getting notified for discarded events

### ISSUE THREAD

**Issue by fm1ch4** [spring-projects/spring-statemachine#802]
If a state has 2 external transitions on 2 different events, in a concurrent environment if each event is sent at the same time, both would be accepted but only 1 would be processed. Is there a way to get notified that the other event got discarded?

Ex.
```
    transitions
        .withExternal()
            .source(State.S1)
            .target(State.S2)
            .event(Event.E1)
            .action(someActionThatTakeAWhile())
            .and()
        .withExternal()
            .source(State.S1)
            .target(State.S3)
            .event(Event.E2)
            .action(someActionThatTakeAWhile());

new Thread(() -> stateMachine.sendEvent(Event.E1)).start() // sendEvent returns true
new Thread(() -> stateMachine.sendEvent(Event.E2)).start() // sendEvent returns true
```

Let's say Event.E1 wins the race and Event.E2 is dropped, even though both were accepted. Is there a way to know Event.E2 got discarded? Or is there some better way to handle this?

Thanks!

**Comment by jvalkeal** [comment]
This is not really possible until we get `3.x` out where reactive api's has been adjusted for these type of needs. Just added one more test how it works 

https://github.com/spring-projects/spring-statemachine/blob/9e0bdae46fd80b2242c61149cf3d08987a9feedf/spring-statemachine-core/src/test/java/org/springframework/statemachine/ReactiveTests.java#L142-L159
