### ISSUE TITLE
Do we have a mechanism where if guard is return false some other actions can be called to perform some functionlity ?

### ISSUE THREAD

**Issue by guptaami** [spring-projects/spring-statemachine#819]

**Comment by jvalkeal** [comment]
No we don't as guard is just a condition evaluation so there really should not be any side effects. Though as you can fully implement guards yourself so you've free to add any hooks there for that particular guard. Thought I would not recommend to hooks into these as it's kinda against whole statemachine concept.
Also as guard usage usually is `if/elseif/else`, part in `else` could also implement these `false` scenarios`.
