### ISSUE TITLE
why spring statemachine do not support set any state after build a new statemachine ？

### ISSUE THREAD

**Issue by huweidada** [spring-projects/spring-statemachine#853]
i just want to recover state machine by a state field。but i have to use persist mechanism。it's
very bad。

**Comment by lion000** [comment]
i think you can try use 
StateMachinePersister StateMachinePersist

**Comment by jvalkeal** [comment]
Persist/Restore is currently a way to do it. While machine is running or constructed all state changes need to happen from transitions which are coming either from events or timers.
