### ISSUE TITLE
StateMachineBuilder.Builder return StateMachineFactory

### ISSUE THREAD

**Issue by xJoeWoo** [spring-projects/spring-statemachine#854]
[`build()` method in `StateMachineBuilder.Builder`](https://github.com/spring-projects/spring-statemachine/blob/da9c68f4e639097878784fb625f0b6ee74f9231e/spring-statemachine-core/src/main/java/org/springframework/statemachine/config/StateMachineBuilder.java#L128) creates an `ObjectStateMachineFactory` each time building the state machine. 

Since the builder configuration usually will not change, what about returning the factory object to developer for more effective build? Returning the factory also adds connection between `StateMachineBuilder.Builder` and `StateMachineFactory` so we don't need to handle two "factory like" type in development.

Or can the factory just be cached in builder for faster build?

**Comment by jvalkeal** [comment]
Right, polished a PR commit and accidentally marked #845 in it.
