### ISSUE TITLE
How to find out next transition?

### ISSUE THREAD

**Issue by sunsriva** [spring-projects/spring-statemachine#857]
I'm building a gui based application in which when state machine get started I want to return what are the next transition available to the user. I looked into docs to check how can we find out next transition in state machine but unable to find. So is there a way to do so?

**Comment by jvalkeal** [comment]
This is notoriously difficult thing to implement and relates to #44. There is no reliable way to do it as you would need to predict future as transition choice can be dynamic depending how machine is configured.
