### ISSUE TITLE
How to get same instance of state machine?

### ISSUE THREAD

**Issue by sunsriva** [spring-projects/spring-statemachine#858]
I have a situation in which on one api call I'm statrting the spring state machine and on other api call I'm triggering the transition. To trigger the transition I need to obtain the instance of state machine which I started earlier in my api call. Is there a way to obtain the instance of same state machine?

**Comment by jvalkeal** [comment]
Looks like this is a use case for [StateMachineService](https://docs.spring.io/spring-statemachine/docs/2.2.0.RELEASE/reference/#sm-service). `DefaultStateMachineService` takes `StateMachineFactory` and allows you to centrally control machines.
