### ISSUE TITLE
Is there a way to build a state machine by rest api?

### ISSUE THREAD

**Issue by WinSon-XiaoYin** [spring-projects/spring-statemachine#869]
Is there is a way to build a state machine by an external rest request? 
This request should contain all the stateData, transitonData and configurationData.
How to pass the actions and guards by this request as well?

**Comment by jvalkeal** [comment]
Currently no as this would be a very opinionated feature. Theoretically one could expose or build api's to manage configs if those a stored in a db/repository but there is too much things to configure so something like this be usable.
