### ISSUE TITLE
AbstractPersistingStateMachineInterceptor does not pass event to context

### ISSUE THREAD

**Issue by sanyarnd** [spring-projects/spring-statemachine#870]
https://github.com/spring-projects/spring-statemachine/blob/2.2.0.RELEASE/spring-statemachine-core/src/main/java/org/springframework/statemachine/persist/AbstractPersistingStateMachineInterceptor.java#L196

What's exactly the reason to not pass an event and event headers?
Perhaps we can enrich context from the message?

**Comment by sanyarnd** [comment]
Solution might look something like this:
https://github.com/spring-projects/spring-statemachine/blob/8b9a7a11d405094649c9c9310dae73758a489dcf/spring-statemachine-core/src/main/java/org/springframework/statemachine/persist/AbstractPersistingStateMachineInterceptor.java#L196

```kotlin
        // NEW: add information about events
        var headers: MessageHeaders? = null
        var payload: E? = null
        if (message != null) {
            headers = message.headers
            payload = message.payload
        }

        return DefaultStateMachineContext(
            childRefs,
            childs,
            id,
            payload,
            headers,
            extendedState,
            historyStates,
            stateMachine.getId()
        )
```

**Comment by jvalkeal** [comment]
Looks like this might have been oversight last times this class got changed. I think you're right what you proposed.

**Comment by jvalkeal** [comment]
I'll shim `buildStateMachineContext`, pass message and deprecate old method.
