### ISSUE TITLE
Double invokation in interceptor

### ISSUE THREAD

**Issue by sanyarnd** [spring-projects/spring-statemachine#871]
https://github.com/spring-projects/spring-statemachine/blob/8d0f7f0268566fbb34f84208512ba48f3b4d1150/spring-statemachine-core/src/main/java/org/springframework/statemachine/support/StateMachineInterceptorList.java#L99

We're using a database to persist state machine context via interceptor, and I see double queries in logs.

```
	public void preStateChange(State<S, E> state, Message<E> message, Transition<S, E> transition,
			StateMachine<S, E> stateMachine, StateMachine<S, E> rootStateMachine) {
		for (StateMachineInterceptor<S, E> interceptor : interceptors) {
			interceptor.preStateChange(state, message, transition, stateMachine);
			interceptor.preStateChange(state, message, transition, stateMachine, rootStateMachine);
		}
	}
```
Can you explain why there are 2 similar calls to interceptor? Same thing with postStateChange method by the way.

**Comment by jvalkeal** [comment]
I think this was because we needed to pass on root machine(for some internal region features) and didn't want to break existing method signatures. Should not cause any issues if you use only only one of those methods?

**Comment by sanyarnd** [comment]
The code is called from `StateMachineInterceptorList`, and there is no way to replace this behaviour.

**Comment by jvalkeal** [comment]
I'm not sure I quite understand this double call. If you just use
```
	void preStateChange(State<S, E> state, Message<E> message, Transition<S, E> transition,
			StateMachine<S, E> stateMachine, StateMachine<S, E> rootStateMachine);
```
where is it called twice?

**Comment by jvalkeal** [comment]
https://github.com/spring-projects/spring-statemachine/blob/1fee6ea556331e46876859353dd36ec6efe8452e/spring-statemachine-core/src/main/java/org/springframework/statemachine/persist/AbstractPersistingStateMachineInterceptor.java#L84-L88

doh! you're right I didn't look deep enough.

**Comment by sanyarnd** [comment]
@jvalkeal so what is an estimated release date for `2.2.1`? Perhaps it can be released as is, 5 fixed bugs is enough.

**Comment by AdrinkBeer** [comment]
I tested the behaviour in 2.2.1 but I still have the method called twice. What about you @sanyarnd ?

**Comment by sanyarnd** [comment]
I see the same code
```java
public void postStateChange(State<S, E> state, Message<E> message, Transition<S, E> transition,
        StateMachine<S, E> stateMachine, StateMachine<S, E> rootStateMachine) {
    for (StateMachineInterceptor<S, E> interceptor : interceptors) {
        interceptor.postStateChange(state, message, transition, stateMachine);
        interceptor.postStateChange(state, message, transition, stateMachine, rootStateMachine);
    }
}
``` 
in `StateMachineInterceptorList`, so I guess bug is not fixed (?)

@jvalkeal

**Comment by jvalkeal** [comment]
Both `postStateChange` methods are called but double call in `AbstractPersistingStateMachineInterceptor` was removed. If there's a custom interceptor then it should use same logic. We can drop that double call when deprecated method is removed. This is my current understanding unless I've forget/mixed something.

**Comment by AdrinkBeer** [comment]
@jvalkeal I think my issue comes from `RegionPersistingInterceptorAdapter `in `AbstractStateMachineFactory`. Actually, my custom interceptor is then used by the factory to create a `RegionPersistingInterceptorAdapter `and this adapter has the 2 methods `postStateChange `overided and calling the same method of the actual interceptor (in my case, the `AbstractPersistingStateMachineInterceptor`).
After that, the original double call is from `StateMachineInterceptorList`.

**Comment by jvalkeal** [comment]
Think we're on a same page. In 2.2.x it's a bad behaviour and custom interceptor needs not to pick both methods. What comes for 2.3.x/2.4.x (it's long overdue to release these) which simply aligns boot deps we can actually drop deprecated methods so that originating double call will go away. Boot will release new versions hopefully today so I can start prep for releases.
