### ISSUE TITLE
what is spring-statemachine-samples-web password or username ?

### ISSUE THREAD

**Issue by lengrongfu** [spring-projects/spring-statemachine#874]
![image](https://user-images.githubusercontent.com/15009201/94354909-30edc680-00b2-11eb-86d5-aa855fc1a040.png)

![image](https://user-images.githubusercontent.com/15009201/94354932-524eb280-00b2-11eb-9340-b65fa32889bc.png)

**Comment by jvalkeal** [comment]
Security got enabled with boot changes and password got printed in a console and default username was `user`. Security in now disables in a sample so it doesn't ask it anymore.
