### ISSUE TITLE
3.0.0.RC1 sendEvent of Mono<Message> returns Flux<StateMachineResult>

### ISSUE THREAD

**Issue by msanssouci** [spring-projects/spring-statemachine#922]
I am checking out the reactive implementation in 3.0.0.RC1. I noticed that the sendEvent method that accepts a `Mono<Message>` returns a `Flux<StateMachineResult>`. My understanding, based off of the post https://spring.io/blog/2020/12/11/spring-statemachine-3-0-0-rc1-released,  is that publishing a single Message would result in a single StateMachineResult. 

Is the blog post correct or is the implementation correct? If the blog post is incorrect, can you provide an example of how a single Message can produces multiple results?

**Comment by jvalkeal** [comment]
This was done like this mostly because in case of statemachine having regions you'd get results back from more than one machine(region). However now that you mentioned it like this I'm kinda questioning that particular choice. It was a little mistake in a blog how I wrote it.

**Comment by msanssouci** [comment]
Thanks for the timely response @jvalkeal! That makes sense. So, if we are using simple statemachine without regions, we can simply act on the first StateMachineResult emitted.

**Comment by jvalkeal** [comment]
Yes, that's it. I'm going to add some sugar to api and add some notes to docs about this.
