### ISSUE TITLE
RepositoryStateMachineModelFactory failed to create ChoiceData

### ISSUE THREAD

**Issue by danieldingzju** [spring-projects/spring-statemachine#934]
My project use RepositoryStateMachineModelFactory to extend StateMachineModel Persistent, just simple override the **resolveAction** and **resolveGuard** methods.
Lately I encounter that the following transitions start from the CHOICE node will not execute the actions, then I study the source code and found that RepositoryStateMachineModelFactory's build logic with CHOICE node ignore the transitions' action while constructing the **ChoiceData**.

**Comment by jvalkeal** [comment]
Thanks, looking the PR, I think it has been an oversight indeed.
