### ISSUE TITLE
WithStateMachine annotation is not supported when StateMachineFactory.getStateMachine uses empty id or dynamically generated id

### ISSUE THREAD

**Issue by gvagenas** [spring-projects/spring-statemachine#940]
When using StateMachineFactory generated state machine with either empty `id` or a dynamically generated `id`, for example:

- `factory.getStateMachine();`
- `factory.getStateMachine(myDynamicGeneratedID);`

its not possible to have `@WithStateMachine(id = "some-id")` because id is not know before runtime.

**Comment by gvagenas** [comment]
PR https://github.com/spring-projects/spring-statemachine/pull/941

**Comment by rbento** [comment]
This is a very important fix which actually makes the StateMachineFactory very useful.
I tested this with version 3.2.0 and it works but that will require to go reactive.
Will this fix be also be available in versions 2.5.X?
Thanks.

**Comment by rbento** [comment]
Good day, any chance for this fix to be applied to version 2.5.X? 
I tested the latest version 3.2.0 and it works but also "forces" to go Reactive.
