### ISSUE TITLE
mutilple statemachine instance support

### ISSUE THREAD

**Issue by quxiaojing** [spring-projects/spring-statemachine#95]
any idea whether spring statemachine can fit in with this situation:

there are many instance of  DomainX, each have their own state,  and their behavior all need to be ruled by the same statemachine configuration.

**Comment by jvalkeal** [comment]
Yes, have you checked our ref docs http://docs.spring.io/spring-statemachine/docs/1.0.0.M3/reference/htmlsingle/#sm-factories

**Comment by quxiaojing** [comment]
@jvalkeal  got it, thanks！ 
PS: where can i place the id of DomainX in the statemachine Instance？

**Comment by jvalkeal** [comment]
If you really need to keep something inside a machine, use extended state variables. If it's just external mapping, use Map<String,StateMachine> or dedicated bean names of you create machine as a bean.

**Comment by quxiaojing** [comment]
@jvalkeal  can i get a non-initial state from statemachine factory by specify the state name？or somehow set the current state of the statemachine？  because sometime we need to load the statemachine from some persistance storeage

**Comment by jvalkeal** [comment]
well yes, it's all mentioned in ref docs, especially in `persist` sample. There's even a persist `recipe`.

**Comment by quxiaojing** [comment]
@jvalkeal  thanks, i will take a closer look at the ref docs
