### ISSUE TITLE
How to support multi initial states?

### ISSUE THREAD

**Issue by HaojunRen** [spring-projects/spring-statemachine#964]
I have 4 states A,  B, C, D and normal flow is A -> B -> C  -> D, but sometime it may be B -> C  -> D

So how can spring-statemachine this feature? Thanks

**Comment by Donquih0te** [comment]
It can be performed with a junction

**Comment by jvalkeal** [comment]
Indeed that can only be one initial state, choice/junction is a one to pick different path after that initial state.
