### ISSUE TITLE
spring-statemachine support skip state?

### ISSUE THREAD

**Issue by Alexhuihui** [spring-projects/spring-statemachine#965]
eg: A -> B -> C -> D，A -> C -> D.
The difference mentioned above are A -> B and A -> C,   judgment condition is event. The spring-statemachine support that?

**Comment by Donquih0te** [comment]
It could be performed something like this:
```
.withExternal()
      .source(State.A)
      .event(Event_1)
      .target(State.B)
      .and()
.withExternal()
      .source(State.A)
      .event(Event_2)
      .target(State.C)
      .and()
```

**Comment by jvalkeal** [comment]
If you can't change event itself, then one other option is to use choice where you can setup guards to pick path dynamically.
